### ISSUE TITLE
manpage downloads 404

### ISSUE THREAD

**Issue by CouldBeThis** [ogham/exa#1036]
On the [linux](https://the.exa.website/install/linux) and [mac](https://the.exa.website/install/macos) install pages, all the links to manpages and shell completion are 404. 

I see the manpages are located here as `.md` only: https://github.com/ogham/exa/tree/master/man

It would be really nice to have a copy/paste install line for these if that's possible for the lazy. :) I also noticed that I already have a manpage at `exa(4)` so if there is some special way to call the page for *this* `exa` given a conflict that would be something to mention. If it'll default to `(1)` then that's good for me. 

I was looking around for the manpage but all I could [find](https://manpages.debian.org/testing/exa/exa.1.en.html) is the same as is obtained by `exa --help`. 

Whenever the manpages are found, I'd like to submit them to https://github.com/jacksonp/ManKier-extra because [mankier](https://www.mankier.com/) is the nicest formatted manpage website. :)

**Comment by ariasuni** [comment]
> On the [linux](https://the.exa.website/install/linux) and [mac](https://the.exa.website/install/macos) install pages, all the links to manpages and shell completion are 404. 

We already have an issue for this, see #757. They are in the downloads, e.g. https://github.com/ogham/exa/releases/download/v0.10.1/exa-accoutrements-v0.10.1.zip.

> I see the manpages are located here as `.md` only: https://github.com/ogham/exa/tree/master/man

They are generated by pandoc from these files, see here:
https://github.com/ogham/exa/blob/42659f93456d9ff7cc1096cbd84d778ede26d76e/Justfile#L99-L102

> I also noticed that I already have a manpage at `exa(4)` so if there is some special way to call the page for *this* `exa` given a conflict that would be something to mention. If it'll default to `(1)` then that's good for me.

Didn’t know about [exa acceleration architecture](https://www.mankier.com/4/exa), but I’m not sure if it’s used or even in development anymore. If you want to access `exa(1)`, just use `man 1 exa`.

> Whenever the manpages are found, I'd like to submit them to https://github.com/jacksonp/ManKier-extra because [mankier](https://www.mankier.com/) is the nicest formatted manpage website. :)

I guess that could be nice, but I’m not sure what the policy is regarding package version. We have people use different versions of exa, especially because of Ubuntu and Debian providing an older version of exa. At least we already have it, for the version available in Arch Linux, anyway: https://man.archlinux.org/man/community/exa/exa.1.en

**Comment by CouldBeThis** [comment]
thanks @ariasuni I didn't find that issue when I searched. and thanks for the other useful info.

Is fixing it just a matter of nobody having the time? because I can make a PR based on the above. I can't locate a repo, branch or anything for the website though so perhaps it is not possible.

**Comment by ariasuni** [comment]
There’s no repository, the original author @ogham is managing the website but he has been unresponsive for a few months, and didn’t answer to my last e-mail. I guess at some point I’ll fork the repo and create a new website, but with my day job, I don’t have that much time to dedicate to exa, I already struggle a lot with reviewing and merge PRs.

**Comment by ariasuni** [comment]
Closed in favor of https://github.com/ogham/exa/issues/757

exa is unmaintained, use [the active fork eza](https://github.com/eza-community/eza) instead (see https://github.com/ogham/exa/issues/1243).
