### ISSUE TITLE
question about the website

### ISSUE THREAD

**Issue by alexzanderr** [ogham/exa#1052]
hello

i love the way the website looks.
i didnt find the source code of the [`website`](https://the.exa.website).

is there a github repo or another repo that hosts the website ?

i love the design and i want get inspiration from it.

any ideas ?

and also, it is built with markdown ?

**Comment by ariasuni** [comment]
No, it’s not available anywhere, but can certainly prettify and copy some part of the CSS, or use the devtools of your browser to copy specific properties, colors, etc.

The author is not responsive since several months so your question about markdown isn’t very likely to be answered any time soon, sorry.

I’m gonna close this to not let it rot, and keep the amount of issues manageable.
