### ISSUE TITLE
wrong icons!

### ISSUE THREAD

**Issue by RAprogramm** [ogham/exa#1059]
v0.10.1 [+git]
after installing nonicons to neovim and add this line to kitty.conf this happened. help me please
![Window_2022-04-24-41_497x289](https://user-images.githubusercontent.com/70325462/164982079-a707e3a1-a627-499a-8ca6-331822a75b50.png)
![Window_2022-04-24-29_328x29](https://user-images.githubusercontent.com/70325462/164982109-dd0cd07f-447c-48cb-814c-1d072b0c1c24.png)

**Comment by RAprogramm** [comment]
in my neovim all is good, but un terminal problem whith wrong icons
![Window_2022-04-24-02_73x744](https://user-images.githubusercontent.com/70325462/164982208-ea5bb27a-bae6-4d9d-bac1-725f01c8f85f.png)

**Comment by ariasuni** [comment]
Well, exa uses [Nerd Fonts](https://www.nerdfonts.com/), so if you’re using a different font it’s gonna be messed up, yes.

**Comment by RAprogramm** [comment]
It is Nerd Font. I know that

**Comment by ariasuni** [comment]
Well, you’re telling Kitty to use nonicons for a specified range of Unicode characters (which is why it works in Neovim), but this range of Unicode characters overlaps with Nerd Fonts, so icons from nonicons end up replacing icons from Nerd Fonts.

There really is nothing we can do on exa’s side, it’s a conflict between Nerd Fonts and nonicons and could only be resolved by one of this font, or if you stop using nonicons and find a way to use Nerd Fonts in Neovim instead.
