### ISSUE TITLE
exa -t 

### ISSUE THREAD

**Issue by mstankus** [ogham/exa#1084]
I am using exa as an ls replacement. So my shell replaces "ls" with "exa" automatically. The one problem which I have found is that when I type "ls -t", it changes it to "exa -t", but this does not work because there are additional choices to be made. Could you pick the one which is most like ls.

Thanks.

**Comment by KKRainbow** [comment]
agree, suffer the same.

**Comment by eggbean** [comment]
If it's a problem you can make a shell function to check for that switch and replace it, or you can make a wrapper script. [I made this one](https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8) so that I can use the same switches as ls and so that the output is sorted in the direction, etc.

**Comment by ariasuni** [comment]
See https://github.com/ogham/exa/issues/519
