### ISSUE TITLE
Respect .gitignore outside of active Git repositories

### ISSUE THREAD

**Issue by Aehmlo** [ogham/exa#1129]
Currently, `exa` appears to only respect `.gitignore` files if they are contained within active Git repositories. I recently found myself in a situation where I wanted to hide a fair number of files from `exa -T` per the `.gitignore` settings, and was surprised that `exa -T --git-ignore` didn't do what I wanted.

I'd be happy to send a patch for this if there's interest (but could use some guidance on, e.g., whether it'd be better as an opt-in option or a change to default behavior).

**Comment by Aehmlo** [comment]
After some further digging, it looks like `.gitignore`-related tasks are [handled through `git2`](https://github.com/ogham/exa/blob/e385cd58da9d2e86425250b108e87e4a69904f5c/src/fs/feature/git.rs#L260), which makes sense, but means that this is probably more work to implement than I expected (short of doing something like bringing in [`ignore`](https://crates.io/crates/ignore), but that's obviously a nontrivial change).

**Comment by ariasuni** [comment]
It would mean doing something horrible, or reimplementing the feature from scratch, in both case a lot of work for such an edge case. I’m gonna close this issue since it has no chance of ever being implemented.

See other related issues, maybe one of them would work for you: https://github.com/ogham/exa/issues/97, https://github.com/ogham/exa/issues/470, https://github.com/ogham/exa/issues/958

I’m open to other suggestions, especially if it’s something that’s already implemented in other such tools like ripgrep, fd and the like.
