### ISSUE TITLE
Files created with bzip3 don't color correctly

### ISSUE THREAD

**Issue by saltedcoffii** [ogham/exa#1134]
If exa does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

```
$ exa --version
exa - list files on the command-line
v0.10.1 [+git]
https://the.exa.website/
```
- No command line operators
- Arch Linux x86-64 rolling

Files created with [bzip3](https://github.com/kspalaiologos/bzip3) don't highlight correctly like other compressed archives. See the attached image:
![image](https://user-images.githubusercontent.com/55339220/195849436-77f284e2-f3ad-4b48-a20a-cf9ce092eb50.png)

**Comment by eggbean** [comment]
Are you not using `dircolors`? Make a file for `dircolors` to form the `LS_COLORS` environment variable to set colours for every filetype that you want.

https://wiki.archlinux.org/title/Color_output_in_console#ls

**Comment by saltedcoffii** [comment]
ah okay. I didn't know `exa` used the LS_COLORS variable. I'll open an issue with coreutils. Closing this issue, it can be marked as invalid if need be.

**Comment by ariasuni** [comment]
Before applying `LS_COLORS`  or `EXA_COLORS`, documented in [`man 5 exa_colors`](https://man.archlinux.org/man/exa_colors.5), exa uses its own colors. So I’m re-opening this, because I think that exa should support `bz3` for colors and icons.

For looking to add this, here’s the code where `bz3` should be added:

https://github.com/ogham/exa/blob/e385cd58da9d2e86425250b108e87e4a69904f5c/src/info/filetype.rs#L82
https://github.com/ogham/exa/blob/e385cd58da9d2e86425250b108e87e4a69904f5c/src/output/icons.rs#L126-L128

**Comment by ariasuni** [comment]
Closing this, since exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and this has been done in [the active fork eza](https://github.com/eza-community/eza). Thanks anyway!
