### ISSUE TITLE
[Question] Is this project still being actively maintained?

### ISSUE THREAD

**Issue by alshdavid** [ogham/exa#1139]
I see there are no changes in 7 months and 38 open pull request - is this project still being actively maintained?

**Comment by roland-rollo** [comment]
@ogham  gave `exa` to @ariasuni  many months ago and stopped developing it himself. @ariasuni  in turn, accepted various changes and tried to push new release but `exa` is a big project, and she was alone, and now she doesn't have time either, so at the moment the project is suspended in space and time.

**Comment by ariasuni** [comment]
More info:

- @ogham gave me a lot of rights on this project, though our agreement was still that it was his project (at the time), but it seems he’s less available than ever (but so am I)
- I’m more or less in burnout and also have physical health issues, [one hundred other things in my life] and I couldn’t find enough focus to properly review some of the big, older PRs
- The best way to help is maybe for people to review some of these big PRs, especially the Windows one since I don’t know anything about Windows dev (I *could* merge PRs that have enough serious reviews)
- I still want to take care of this project, but I don’t know when I’ll have time again (hopefully soon, but well…)

**Comment by jnordwick** [comment]
i could her with some of the prs. im generally in favor of rewriting old unix utils to be more power and better to use, but i refuse to support snap in any way.  so im a little torn.

**Comment by polarathene** [comment]
I think there are some rust organizations on Github where `exa` could perhaps be migrated to given the limited availability of maintainers here to review and merge? That should allow for trusted maintainers to keep the project healthy?

The last release was April 2021 `v0.10.1` and that remains the version in `Cargo.toml`, at first I thought Github releases just weren't being made anymore (_likewise for the `cargo install exa` crate_).

Any bug reports since that reference git builds may also need to take into account when the report was made as the amount of changes continue to pile up. A release is probably worthwhile pursuing, but if current maintainers of the project aren't likely to be available to do that (_for understandable reasons, no pressure_), it's not good for the projects health? (_I noticed the [Oct 2022 issue requesting a new release](https://github.com/ogham/exa/issues/1135) was closed recently to link back to here_)

- There is [this org](https://github.com/rust-unofficial/about), but it's difficult to see at a glance if that's relevant anymore. 
- There's quite a few popular rust CLI projects actively maintained by [`sharkdp`](https://github.com/sharkdp). Might be an option, but I could understand if that is less appealing than a proper community org.
- I'm not sure if the [Rust CLI WG](https://github.com/orgs/rust-cli/repositories) org would adopt the project, but at a glance it looks like it might be appropriate?
- Could additionally reach out to communities like `r/rust`?

**Comment by hernangonzalez** [comment]
I think @polarathene has a sensitive suggestion here. Even very small PRs have been hanging for a while, and would be sad to see people moving away cause of maintenance.

**Comment by InCogNiTo124** [comment]
> There is [this org](https://github.com/rust-unofficial/about), but it's difficult to see at a glance if that's relevant anymore.

Regarding this, I deep dived a bit so I'll live a couple of my cents here: @rust-unofficial states that the project should have an active maintainer before joining the organization, something this project does not seem to be having. But, I can see it being relevant.

nevertheless great suggestions @polarathene. I think the best course of action is contacting `r/rust` or other communities for a possible replacement maintainer, and if someone decides they're willing to either contact rust-unofficial or create a new organization for exa. In the meantime, a great addition would be a list of PR's that are ready to be merged.

**Comment by syphar** [comment]
@ogham @ariasuni  

I would love to help maintaining this project. I'm actively using `exa`, and would really like to see some of the improvements get released. 

If not possible / wanted I would alternatively create a fork, and start merging open PRs from this into it.

**Comment by cafkafk** [comment]
> I would love to help maintaining this project. I'm actively using `exa`, and would really like to see some of the improvements get released.
> 
> If not possible / wanted I would alternatively create a fork, and start merging open PRs from this into it.

It would probably be wise to get someone with the ability to merge PRs that is actually active on the project, maybe @syphar should consider a deadline for a reply until you just fork it, it's a shame to see all these wasted contributions piling up.

Right now I'd love to try and help by reviewing some PRs, but it is unclear if that would even matter, given it doesn't seem there's anyone to merge them that's active.

**Comment by sbatial** [comment]
@syphar Should there be any development regarding the fork: I can try and help with reviews as well. I should have some more spare time in the next few months so feel free to ping me.

General thought:
I'm not sure if I'm missing something but a fork should not go against @ariasuni stated desire to be able to maintain again.
As far as I understand if that is the case the fork can just be merged into the original if a maintainer is willing to do so.?


And to @ogham and @ariasuni: Thanks for the project.
But health is more important. Take care.

**Comment by syphar** [comment]
> @syphar Should there be any development regarding the fork: I can try and help with reviews as well. I should have some more spare time in the next few months so feel free to ping me.
> 

@sbatial this sounds awesome! 
For now I just [created the repository](https://github.com/syphar/zetta), merged the one PR that I wanted (relative time-style, #1061 ), and reduced the documentation / automations for installation procedures. 

Then I got sidetracked by needed work on docs.rs itself so I couldn't invest more time into it around the open PRs. Any help is appreciated. 


> General thought:
> I'm not sure if I'm missing something but a fork should not go against @ariasuni stated desire to be able to maintain again.
> As far as I understand if that is the case the fork can just be merged into the original if a maintainer is willing to do so.?

yep, merging back should totally be possible.

**Comment by dhruvkb** [comment]
I would like to point out an alternative I'm working on, called [`pls`](https://dhruvkb.github.io/pls): https://github.com/dhruvkb/pls. It's still fairly new and not as mature as exa but the core functionality is there. I appreciate your feedback.

**Comment by eggbean** [comment]
> I would like to point out an alternative I'm working on, called [`pls`](https://dhruvkb.github.io/pls): https://github.com/dhruvkb/pls. It's still fairly new and not as mature as exa but the core functionality is there. I appreciate your feedback.

This looks promising, but `pls does not maintain compatibility with ls(1) at all` put me off. I made `exa` work as closely to `ls` as I could by making [this wrapper script](https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8). Would this not be possible in `pls` using its yaml configuration?

**Comment by dhruvkb** [comment]
@eggbean I meant that the CLI API is not the same between pls and ls (different flag names and more customisation options). You can use something like a wrapper script or shell aliases to get outputs very similar to that provided by `ls` or `exa`.

**Comment by cafkafk** [comment]
I (also) made another fork (I duplicated all PRs from exa using a shell script)

Currently I've got 57/63 PRs left, so 6 PRs have are closed/merged, and a lot have been labeled/gotten comments on next steps. 

So far I've found more than a few duplicates.

I'm trying to make it so exa can pull all the pr's when they are merged, if exa ever becomes active again.

https://github.com/cafkafk/eza

currently merged:
- selinux contexts support
- git repo statuses
- fish -i/--inode fixes

I'm working through the PRs now, and seeing how many I can get through this weekend. But there are many places I'd like to get some feedback and I'm also lloking for people that are willing to test PRs.

https://github.com/cafkafk/eza/pulls

**Comment by ariasuni** [comment]
Hi all.

I’m starting to feel a bit better after quitting my dayjob. I’ll try to go through the backlog of issues and MRs on here, but it’s a lot and I may not be very active so it could take some time. I also want to finish some older MR that I think would greatly benefit exa.

Ideally, I would like to create a community-owned fork, so we could start having new releases under a proper org. I didn’t have the bandwidth to do then, and I don’t have it now — at least do launch the thing alone.

If you’re interested, we can try to figure out something together and have a real team of maintainers for exa (or whatever the name of the fork), so that we can truly go forward.

**Comment by cafkafk** [comment]
> Hi all.
> 
> I’m starting to feel a bit better after quitting my dayjob. I’ll try to go through the backlog of issues and MRs on here, but it’s a lot and I may not be very active so it could take some time. I also want to finish some older MR that I think would greatly benefit exa.
> 
> Ideally, I would like to create a community-owned fork, so we could start having new releases under a proper org. I didn’t have the bandwidth to do then, and I don’t have it now — at least do launch the thing alone.
> 
> If you’re interested, we can try to figure out something together and have a real team of maintainers for exa (or whatever the name of the fork), so that we can truly go forward.

I'd really love if you could take a look at [eza](https://github.com/cafkafk/eza), I (and a few others) have already gotten a lot of backlog and bugs cleared, and I'd be fine with adding you as a contributor and down the line creating a community org.

**Comment by cafkafk** [comment]
> Ideally, I would like to create a community-owned fork, so we could start having new releases under a proper org. I didn’t have the bandwidth to do then, and I don’t have it now — at least do launch the thing alone.

To keep the ball rolling I created https://github.com/eza-community, and transferred the ownership of [eza](https://github.com/eza-community/eza) to it.

For now I have invited you, @sbatial and @syphar. If anyone else wish to join the efforts, they should feel free to ping me.

Of course, all of you are free to go in some other direction, I just am trying my best to take initiative on this so we don't end up in a situation again where we are months without progress. Since last friday, we've gone from 63 open pull requests from exa to 16.

**Comment by cafkafk** [comment]
Also, @mwaitzman, you keep adding those thumbs down emojis, but I have no way to parse what they are actually critical of, could you please elaborate a bit? I'm very open to feedback, if there is some misstep I'd know about it sooner than later so I can adjust accordingly.

**Comment by ariasuni** [comment]
I’ll take a look at eza, this sound promising. I can try to revive important work to open an MR there.

Sadly I don’t have access to exa’s repository setting (to put it in an archived state) but I can put a link in the README to an active fork.

**Comment by polarathene** [comment]
So, going forward the project won't continue as `exa`? I'd have thought that would have been ideal to retain the name and `eza` was going to merge all the work back into `exa` which would then be migrated to an organization to ensure ongoing maintenance/development continues without this issue occurring again?

**Comment by cafkafk** [comment]
> So, going forward the project won't continue as `exa`? I'd have thought that would have been ideal to retain the name and `eza` was going to merge all the work back into `exa` which would then be migrated to an organization to ensure ongoing maintenance/development continues without this issue occurring again?

Without oghams stamp of approval, I felt it was wrong to take the name.

**Comment by mentalisttraceur** [comment]
> Without oghams stamp of approval

Well then... @ogham can you please bless an active community-maintained fork using the `exa` name?

**Comment by polarathene** [comment]
@mentalisttraceur you'll have to reach out via other means. They've not had any github activity since Oct 2021, close to 2 years.

**Comment by bb010g** [comment]
> @mentalisttraceur you'll have to reach out via other means. They've not had any github activity since Oct 2021 (_on their profile activity graph at least_), close to 2 years.

I took the liberty of emailing Ben about this. Hopefully we'll get a response soon.

**Comment by ariasuni** [comment]
Unpinning this issue in favor of this new one I created, to redirect people to eza:
https://github.com/ogham/exa/issues/1243
