### ISSUE TITLE
Show only hidden files

### ISSUE THREAD

**Issue by faxotherapy** [ogham/exa#1180]
When listing hidden files, I'm most interested by listing hidden files only, instead of listing hiden files with non-hidden files. The trick I use is appending `.??*` as a further argument, e.g.: `exa -lagh --icons .??*`

However, it only works for listing the current directory. I can't do, e.g. `exa -lagh --icons .??* ~/`

**Comment by eggbean** [comment]
You can use the `-d` switch to view directories as files, so that the content don't get listed as well. You need to put your glob pattern after the path. This is the same with `ls`.

eg. 

To view hidden files in the current directory: `exa -laghd --icons .*`

...in the parent directory: `exa -laghd --icons ../.*`

--in any directory: `exa -laghd --icons <PATH>/.*`
