### ISSUE TITLE
cargo build failed: could not compile gcc

### ISSUE THREAD

**Issue by monnand** [ogham/exa#12]
I think this may not be an issue. But I did not find any other place to seek for help. So I have to report it as an issue. Sorry for the possible abuse of the issue list.

I compiled the code using ``cargo build`` but received the following error:

```
/home/monnand/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.2.1/src/lib.rs:61:25: 61:29 error: type `core::option::Option<std::ffi::os_str::OsString>` does not implement any method in scope named `ok`
/home/monnand/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.2.1/src/lib.rs:61     let r = env::var(v).ok();
                                                                                                              ^~~~
error: aborting due to previous error
```

Here are the versions of rustc and cargo:

```
$ cargo version
cargo 0.0.1-pre-nightly (9404539 2015-02-09 20:54:26 +0000)
$ rustc -V
rustc 1.0.0-nightly (134e00be7 2015-02-09 19:01:37 +0000)
```

**Comment by ogham** [comment]
I think you need to update your Rust to a more recent Nightly - try running the rustup script again.

On the 11th, the `std::env` interface was changed so that `std::env::var(v)` returns a Result, instead of an Option: see https://github.com/rust-lang/rust/commit/a828e7948069f310dc5b33be8edb65e5e8e0cf9a for the commit that changed it. It looks like your Rust version is from two days before that, which is back when it just returned an Option, whereas the code for the `gcc` crate was adapted to use a Result. So updating your Rust should fix your build problems.

> Sorry for the possible abuse of the issue list.

Don't worry about it.
