### ISSUE TITLE
--icons working but not for audio files icon

### ISSUE THREAD

**Issue by m010-cpu** [ogham/exa#1217]

**Comment by FrodoBaggins74524** [comment]
ere could be a few potential reasons for this problem. Here are some troubleshooting steps you can try:

Confirm Font and Glyph Support:
Double-check that your chosen font (MesloLGS NerdFont) indeed includes the necessary glyphs for displaying audio file icons. Sometimes, certain icon fonts may not cover all file types. You can visit the NerdFonts website or GitHub repository to verify if the required icons are present in the font you are using.

Clear Font Cache:
If you recently installed the NerdFont or changed your font settings, it's possible that the font cache needs to be cleared. You can try restarting iTerm2 or your terminal emulator and see if that resolves the issue.

Update Font Version:
Ensure that you are using the latest version of the MesloLGS NerdFont. Sometimes, updates to the font might include new glyphs or improvements for existing ones.

Verify File Type Association:
Check that your system correctly associates MP3 files with the appropriate MIME type. This file association ensures that the correct icon is displayed for each file type. Most likely, this should already be set up correctly, but it's worth checking just in case.

Alternative Icon Fonts:
If the above steps don't resolve the issue, consider trying a different NerdFont or icon font that has explicit support for audio file icons. You can find various NerdFonts and icon fonts available online.

Verify exa Configuration:
Confirm that exa, the tool you are using to display the icons, is correctly configured to use the icons from the chosen font. Check the exa configuration and ensure that it is pointing to the correct font and icon set.

Update exa:
Make sure that you are using the latest version of exa. Updates to the utility might include bug fixes or improved support for certain fonts.

Other Terminal Emulators:
If the issue persists and you've exhausted all options, consider trying a different terminal emulator to see if the problem is specific to iTerm2. You can use Terminal.app, Alacritty, or another terminal emulator that supports NerdFonts.
