### ISSUE TITLE
long-iso time style

### ISSUE THREAD

**Issue by yongqli** [ogham/exa#133]
It would be nice to have long-iso style: `2016-12-05 04:23` similar to `ls`.

**Comment by ogham** [comment]
At some point I hope to add customisable date-time formatting strings.

**Comment by ogham** [comment]
From the ls man page:

       --time-style=STYLE
              with -l, show times using style STYLE: full-iso, long-iso,  iso,
              locale,  or  +FORMAT;  FORMAT  is interpreted like in 'date'; if
              FORMAT  is  FORMAT1<newline>FORMAT2,  then  FORMAT1  applies  to
              non-recent  files  and FORMAT2 to recent files; if STYLE is pre-
              fixed with 'posix-', STYLE takes effect only outside  the  POSIX
              locale

It makes it look so easy! exa won't be able to support "true" customisable timestamps with formatting strings and placeholder values and such. It relies on the datetime crate, which *has* support for parsing formatting strings but not a very good one because I haven't updated it in ages.

However, a good stepping stone is to support the strings "full-iso", "long-iso", "iso", and "locale", all for ls compatibility, so that's what this issue's going to be about.

**Comment by ogham** [comment]
My computer doesn't seem to support nanosecond-precision timestamps, but you get the idea:

![Screen Shot 2017-07-06 at 01.01.26.png](https://shipusercontent.com/32046c8789f7ff831773228ecc8eef08/Screen%20Shot%202017-07-06%20at%2001.01.26.png)

I've used "default" for the default one instead of "locale" because it's not quite as locale-y as I'd like, but that's a problem for another day.
