### ISSUE TITLE
Symlink incorrectly shown as broken

### ISSUE THREAD

**Issue by nyuszika7h** [ogham/exa#134]
I don't know why `exa` thinks this symlink is broken (the second instance of `ghc` in the first example is shown in red and underlined), it works fine.

```
nyuszika7h@cadoth ~ > exa -l /usr/local/bin/ghc
lrwxrwxrwx 24 root 14 Apr  2015 ghc -> ghc
nyuszika7h@cadoth ~ > \ls -l /usr/local/bin/ghc
lrwxrwxrwx 1 root staff 24 Apr 14  2015 /usr/local/bin/ghc -> ../stow/ghc-7.10/bin/ghc
```

**Comment by ogham** [comment]
I'll take a look.

**Comment by nyuszika7h** [comment]
My guess is it tries to resolve `../stow/ghc-7.10/bin/ghc` relative to the current working directory (`/home/nyuszika7h`) instead of the directory of the symlink.

**Comment by ogham** [comment]
@nyuszika7h I think you're right!

**Comment by ogham** [comment]
You were right. It actually took me a while to track down, because it only happens when you specify the file directly on the command-line, rather than specifying a directory. I kept on trying to reproduce it by scanning entire directories, so it never showed up!

But yeah, the problem was with relative symlinks when you were running exa in a different directory.

![screen shot 2017-05-15 at 22 33 06](https://cloud.githubusercontent.com/assets/503760/26080432/81212732-39be-11e7-8101-84b8779d4fa7.png)
