### ISSUE TITLE
Indicate if the sticky bit is set

### ISSUE THREAD

**Issue by Stebalien** [ogham/exa#142]
Currently, exa doesn't indicate whether or not the sticky bit is set.

**Comment by ogham** [comment]
Yeah, a file only has nine permissions at the moment. Adding another one will require moving some code around, but it’s possible to do.

**Comment by ogham** [comment]
I tried implementing this today, and the permissions value seemed to be capped at 0o777. Not sure if there’s something else that needs to be done before exa can see the sticky bits.

**Comment by ogham** [comment]
Unfortunately I had to push this back a release because it wasn’t as easy to implement as I thought. I couldn’t get [the `mode` method](https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html#tymethod.mode) to return anything above 0o777, and although one of the other methods will probably give me the numbers I want, I’m not confident enough to pull in something from the libc crate without having it break on some random platform. Sorry!

**Comment by ogham** [comment]
nm i figured it out

**Comment by Stebalien** [comment]
Nice! Thanks.
