### ISSUE TITLE
Provide shell completion

### ISSUE THREAD

**Issue by elyscape** [ogham/exa#150]
It would be quite nice if exa provided Bash and/or zsh completion scripts.

**Comment by ogham** [comment]
I’d like that too.

**Comment by little-dude** [comment]
One way to have this for free would be to use `clap` for the cli, which provides completion for both bash, zsh, and fish. Is this something you would consider @ogham ? If so I could give it a try.

**Comment by ogham** [comment]
@little-dude: I ended up doing things the hard way, and just writing separate files for those three. exa's command-line option parsing is a little up in the air at the moment, and there is a good chance I'll switch to clap — especially because I tried to find out how ripgrep handles completions, only to find out that it uses clap!
