### ISSUE TITLE
Support -A/--almost-all

### ISSUE THREAD

**Issue by elyscape** [ogham/exa#155]
`ls -A` (and, with GNU ls, `ls --almost-all`) lists entries starting with `.`, except for `.` and `..`. Sample output:
```shellsession
scapeless:almost-all elyscape$ ls
somefile
scapeless:almost-all elyscape$ ls -a
.		..		.hidden		somefile
scapeless:almost-all elyscape$ ls -A
.hidden		somefile
```
It would be nice if exa supported this flag as well.

**Comment by Orangenhain** [comment]
I think the output of that third command `ls -A` should be missing the `.` && `..` entries.

**Comment by elyscape** [comment]
Oop, good catch. I mispasted.

**Comment by kballard** [comment]
exa already seems to omit `.` and `..` when using `-a`/`--all`.

**Comment by elyscape** [comment]
Interesting, so it does. In that case, it might be a good idea to move the current behavior to `-A`/`--almost-all` and make `-a`/`--all` show `.` and `..`.

**Comment by kballard** [comment]
I was going to write a comment saying I like the current behavior and there's no real reason to want `.` and `..`, but then I realized there is one use-case: if you're using long mode (`-l`), then you'd get information for `.` and `..` too if they were printed. I don't think I've ever made use of that (if I want to know the info for the current dir I use the `-d` flag), but I can imagine other people may be used to having that.

**Comment by ogham** [comment]
This came up in #43, but that was two years ago! I’m going to leave _this_ one open for discussion purposes, but... I feel like exa has the chance to provide some better defaults here.

Much like reporting the “file size” for directories, just because the information is *there* doesn’t mean it’s useful enough to warrant being displayed. There’s a [StackOverflow question asking why they’re there][so], and the answers state that there are/were two hard links in each directory for the current and parent dirs, and ls dutifully reports that those links exist in its list.

The thing is, I’ve never looked at those two directory entries, not once. If I need to check the permissions or other metadata of `.` or `..`, then I could run `exa -ld . ..`, and check *only* those two lines without having to see all the other entries, or I could run `stat . ..` for a raw view on what’s happening under the hood. All of the other times, I’m not interested in seeing the metadata of those two directories when I’m listing one’s contents, and the fewer lines and less clutter I have on my screen, the better. I have no data for this, but I have a sneaky suspicion that most of the time, when people use `ls -a`, they really want `ls -A` anyway.

So that’s why I didn’t pursue this the first time. And what makes this _even more annoying_ is that if we add the opposite functionality under the `-A` flag or something, then the behaviour is the opposite for how it works in ls: `-a` shows the pair in ls and hides them in exa, and `-A` hides them in ls and shows them in exa. If we keep the convention where an uppercase command-line option is an “even more specific” version of the lowercase option, then people might get confused if they come from ls; if we don’t, then we lose the chance to implement what I consider some saner defaults.

Something that would definitely sway me over to the other side is a case where it _is_ helpful to see a directory’s contents _and_ its pair of hard links at the same time. But if enough people want this feature anyway then I’d be willing to reconsider.

[so]: http://stackoverflow.com/questions/322719/why-do-directory-listings-contain-the-current-and-parent-directory?noredirect=1&lq=1

PS: I accidentally introduced a bug where the filenames for `.` and `..` are blank... so if you do try to run `ls -ld . ..` and are missing a column, that’s why. kballard kindly fixed this in #168.

**Comment by kballard** [comment]
Could we do something like `exa -a -a` (or `exa -aa`) shows `.` and `..`? Similar to the way `-v` works in many tools.

**Comment by ogham** [comment]
That’s a great idea! It’s intuitive, doesn’t have different behaviour than ls, and Rust’s getopts crate supports it too.

**Comment by ogham** [comment]
I started working on this in the [https://github.com/ogham/exa/commits/almost-all](almost-all branch) (which, come to think of it, is completely the wrong name for it)

It works apart from the fact that instead of the `.` directory, it uses the name of the directory instead, but I still have a couple days left to fix that.

**Comment by ogham** [comment]
![screen shot 2017-06-29 at 13 35 03](https://user-images.githubusercontent.com/503760/27687711-cc7acb00-5ccf-11e7-8bdc-ed0b2e0688da.png)

Couple days taken!

**Comment by swrobel** [comment]
@ogham is it possible since the default `-a` behavior is essentially the same as `-A` is on `ls` that `-A` could be accepted as an alias for `-a`. This makes it much easier to drop `exa` in as a replacement for `ls`.

**Comment by swrobel** [comment]
@ogham do you want me to file a separate issue...?
