### ISSUE TITLE
json support

### ISSUE THREAD

**Issue by nrdmn** [ogham/exa#157]
exa should support json output for scripting

**Comment by ogham** [comment]
This is being tracked in #13. It would allow for a lot of scripting!

**Comment by almir-campos** [comment]
> exa should support json output for scripting

Hi. I believe it's labeled as "duplicate" because of it refers to structured file content,right? -Please, correct me if I'm wrong.

However, I was wondering if it's possible just to add the color highlight for the ".json" filenames on  simple  commands like "exa -l".

I never worked with Rust, but I'm willing to try to contribute with this update, if it's not implemented.

Please, let me know.

Thanks.

**Comment by almir-campos** [comment]
UPDATE: I  made the changes I suggested on the previous message and "it's working on my machine." (Have you heard this before? :D )

Here's the Pull Request: https://github.com/ogham/exa/pull/478
