### ISSUE TITLE
Any chance for an OSX version

### ISSUE THREAD

**Issue by JikkuJose** [ogham/exa#16]
Perhaps even a brew formula?

**Comment by iKevinY** [comment]
It would be awesome if exa was available on Homebrew. Is there information anywhere about writing Homebrew formulae for Cargo applications?

**Comment by ogham** [comment]
Sorry, I'm not sure how to write Homebrew formulae. However, https://github.com/brson/rustle has appeared very recently, which promises one-line downloading.

**Comment by iKevinY** [comment]
@ogham When Cargo applications start to appear on Homebrew, would it be alright if I took a shot at writing a formula for exa and submitting it? I can't find any information on doing so at the moment (probably because there are so few Cargo apps and Rust isn't completely stable yet), but I'm sure some resources will arise in the near future.

**Comment by ogham** [comment]
@iKevinY: Absolutely!
