### ISSUE TITLE
configurable colors  [feature request]

### ISSUE THREAD

**Issue by Orangenhain** [ogham/exa#160]
It would be nice if we could have configurable colors.

Not just for the files (based on type) as #116 requests, but for all the other things as well (permissions, types of users, git status, ... whatever [colurs.rs](https://github.com/ogham/exa/blob/master/src/output/colours.rs) allows for.

**Comment by simonwiles** [comment]
I would appreciate this -- the default configuration puts the owner in bold, bright yellow, which makes it stand out ahead of all the other information. This is my own laptop, of course, a single-user system, so generally it is the *least* useful information of all (this is especially awkward in the `--grid` view).  (In fact, tbh, I would remove the owner from my normal `alias`, if that was possible.)

**Comment by derryl** [comment]
I, too, would love to see this. Thanks for building such an awesome tool!

**Comment by frankamp** [comment]
The blue for dates doesn't match the preview on the website frontend, which has lighter dates. The experience I have in my shell is very dark, so much so that it is hard to read.

![image](https://user-images.githubusercontent.com/923726/28948227-35e25b44-7869-11e7-9a95-5db061d238a4.png)

The main website shows something much lighter

![image](https://user-images.githubusercontent.com/923726/28948249-5082e996-7869-11e7-8807-476f3dde12e6.png)

Perhaps this is an issue in its own right? Now that I look at it the font doesn't look the same either. And I see the website is trying to reproduce everything in html rather than screenshot the actual output so maybe my expectations are wrong.

Thanks for making it! I'll come back and check it out again a little down the line.

**Comment by ogham** [comment]
@frankamp You’ve run into one of my long-time pet peeves: terminal emulators that have a horrible default colour for blue! Believe it or not, exa just uses normal blue as its date colour. Not even dark blue, normal blue.

In my opinion this is one of the things standing in the way of more programs adopting colours. If the experience is bad, command-line programs won’t change, and they won’t change, the emulators don’t need to make their colour schemes usable. There’s no reason why one of the standard 16 colours should be unreadable by default.

Anyway, I recommend you change the blue colour because otherwise you’ll start to miss things in other programs too.

**Comment by frankamp** [comment]
@ogham I don't quite understand how color is specified, but from your comment I take it 1) exa specifies a symbolic color, not a hex or other direct representation and  2) its my terminal (something between zsh and/or iTerm in my case) that is at fault for their choice of how to interpret "blue". That's interesting all by itself. It makes me wonder if there is something akin to that direct color representation that would give you more control over what the end user experiences. Again, thanks for putting a thing out in the world.

**Comment by nakal** [comment]
It is not a solution to alter the colors globally, because even the original blue can be usable given it is used on different backgrounds and/or as background color. `ls` tools typically respect something like `LSCOLORS` environment.

I'd like to change the blue color to cyan and maybe adapt some other colors, too.

**Comment by jreidthompson** [comment]
i'll add my name to the list that would like to be able to configure colors -- i also use a scheme that makes some of the colors hard to read and would like to be able to adjust them accordingly

**Comment by kaushalmodi** [comment]
I came across this thread because of the same issue of the dark blue color for dates being difficult to read on black background terminals, as @frankamp reported. Would love to see some way to customize the various field colors, especially that dark blue. 

@ogham How do you change the default blue color of a terminal. I use tmux in xterm.

**Comment by jdanford** [comment]
@kaushalmodi take a look at https://wiki.archlinux.org/index.php/Xterm#Colors

**Comment by kaushalmodi** [comment]
@jdanford Thanks! That helped.

I set these to get a less bright yellow and a lighter blue:

```
! 3 - yellow
XTerm.VT100.color3: rgb:f3/dc/55
UXTerm.VT100.color3: rgb:f3/dc/55
! 4 - blue
XTerm.VT100.color4: cornflowerblue
UXTerm.VT100.color4: cornflowerblue
```

**Comment by ogham** [comment]
Hey, what's going on here?

<img width="590" alt="screen shot 2017-08-31 at 22 21 33" src="https://user-images.githubusercontent.com/503760/29945868-d0b66664-8e9a-11e7-89ab-06a0a943a5f6.png">

;)

(`colors` is a command in the Vagrant VM. Or at least, it will be soon)

**Comment by fth86** [comment]
I really don't agree with the philosophy that seems to be accepted here by everyone: why should I have to change the colors of my surrounding environment (shell) just to change the colours that exa puts on the terminal? Wrong priorities!

*All* heavily-used and tried terminal applications (emacs, vim, GNU source-highlight, git ...) 
let you configure colours separately. As they should. Why should the default configuration of my shell dictate how application output will look like?

The default colour configuration (colour-names:  blue, green, brightred, etc.) is there to assist the user in theming. Not for giving applications the excuse to lack customizability. 

exa looks horrible given my default configuration. That is nobody's fault, just the way things turned out to be. I'd like to be able to change it, most preferably using an environment variable, similar to $LS_COLORS.

**Comment by ariasuni** [comment]
I realize this is very late, but there is an `EXA_COLORS` environment variable now (since a while).

Also, exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and colors are more sensible in [the active fork eza](https://github.com/eza-community/eza).

**Comment by nakal** [comment]
Thank you for the hint with eza. Btw, it seems that the Debian package maintainer doesn't know that exa is dead.
