### ISSUE TITLE
"-t" command-line argument should work as in "ls" (IMHO)

### ISSUE THREAD

**Issue by sergei-dyshel** [ogham/exa#243]
After installing `exa` the first thing I tried to run first was `exa -ltr` which gave me
```
Unrecognized option: '--time r'. (choices: modified accessed created)
```

I guess that `-t` option works differently in `exa` and `ls` and that (IMHO) may be a serious show-stopper for someone wanting to migrate from `ls` to `exa` without remembering new options. 'ls -ltr` such a popular command, that many people (and even some Linux distros) just alias it to `ltr`. You can just try [googling](https://www.google.co.il/search?q=%22ls+-ltr%22&oq=%22ls+-ltr%22&aqs=chrome..69i57.1600j0j7&sourceid=chrome&ie=UTF-8) for it.

PS. May be this issue was raised previously but I couldn't find it (`ltr` is not a good keyword to search for).

**Comment by ogham** [comment]
This is similar to #284, which had the idea to interpret `-t` without any arguments as to sort by time, like ls does. This isn't possible in exa due to the way the options parser works, so I added in some suggestions instead:

<img width="556" alt="screen shot 2017-09-14 at 09 18 37" src="https://user-images.githubusercontent.com/503760/30424760-d7e9f96a-993e-11e7-996e-49019055dad4.png">

Like I said in the other thread, it's not much, but it's *something*.

I think you're right about ls compatibility here: when I was new to the command-line, I wouldn't read through the manual page for ls, but I *would* find a list of common option combinations like `-la` or `-ltr` and just memorise them. I'm fairly certain I even stole `alias ltr=ls -ltr` or something from someone's shell configuration years ago, but until I think of more, these two cases are the only two that offer suggestions like this.

**Comment by eMBee** [comment]
r is not an option for t, but to reverse the output, however that is created,
it should work independently of using -t
