### ISSUE TITLE
Enable --group options without -l / --long option.

### ISSUE THREAD

**Issue by vermaden** [ogham/exa#256]
Currently exa does not allow usage of **--group** option without **-l** / **--long** option which is wrong because if You want to have smilar to GNU **ls** approach that long listing always displays displays groups, then You would wand to set **alias exa='exa --group'** so that with short listing **'exa'** would have default output and with **'exa -l'** you would have long listing with groups. Currently that is not possible and everytime I want to have long listing with groups (default in GNU **ls**) I have to add **-g** flag which is PITA. Now you have to type **exa** or **exa -lg** instead of **exa** and **exa -l**.

```
% exa
Option --group is useless without option --long.

```

**Comment by ogham** [comment]
Hey, this issue is being tracked in #152. Good news, though: I've done some work to make exa's options parser more lenient, and I want to finish it before the next release. So doing `exa --group` and `exa` will do the same thing, and `exa --group --long` will display a long listing with the group column.

**Comment by vermaden** [comment]
Good to hear that, thanks.
