### ISSUE TITLE
<Operation not supported (os error 95)>

### ISSUE THREAD

**Issue by LordHog** [ogham/exa#259]
Hello,

  When I try to use the long option (i.e., `-l`) the output is displaying "<Operation not supported (os error 95)>".  Why am I seeing this?  Is it because exa will not work properly when ssh into a remote machine? Thanks.

Regards,
Mark

**Comment by ogham** [comment]
Hi,

This is being tracked in #178. The error comes because it’s trying to query the extended attribute status of all your files. If you’re using a remote filesystem like nfs or sshfs then it’ll return this error instead of just saying that your file has no attributes.

For the next version I’m going to change this so the error is not displayed unless you explicitly ask for the attributes.

**Comment by LordHog** [comment]
Mr. Benjamin,

 Thanks for the information. Yes, this explains my situation exactly.  Our
home directories are mapped to a NFS.  I look forward to the update so I
can start using exa.

Regards,
Mark

**Comment by ogham** [comment]
@LordHog: I just released v0.8.0, which hides these errors — this should solve your problem.
