### ISSUE TITLE
What is the purpose of --list-dirs option? It seems to be broken

### ISSUE THREAD

**Issue by paulriddle** [ogham/exa#273]
![list-dirs](https://user-images.githubusercontent.com/7285838/29483536-fc41c14e-84c1-11e7-9eec-9d588a3a20e0.png)

It only lists a dot, which doesn't seem particularly useful. I think I'm missing something here. Exa version is 0.7.0.

**Comment by ogham** [comment]
Believe it or not, ls does the same thing:

    $ ls -d
    .

The `--list-dirs` option is a confusing one, so much so that I think I'm going to change its name to something else. Rather than listing *only* directories, the `-d` flag lists directories as though they were regular files, without recursing into them. And exa with no arguments lists the current directory, `.`, so it's showing you the entry for the current directory without recursing into it, which is why you see the dot.

See #202 for more, and some name discussion.
