### ISSUE TITLE
Binary package download validation

### ISSUE THREAD

**Issue by stranskj** [ogham/exa#274]
It would by nice to have some validation of binary package downloaded from the webpage. At least hash, having the hash in comments for commit, which the binary is built from, here for double check would even nicer.

**Comment by ogham** [comment]
Good idea — for the next release I'll put something in place.

**Comment by ogham** [comment]
The [v0.8.0 downloads](https://github.com/ogham/exa/releases/tag/v0.8.0) now include MD5SUMS and SHA1SUMS. And I just ran `gmd5sum -c MD5SUMS` and it immediately failed. oops...

**Comment by ogham** [comment]
I ended up changing the website so that it links to GitHub instead of hosting the binaries itself, because I trust them more than myself to get the security stuff correct (key pinning, less likely to let their SSL cert expire like in #299, etc).

Also, weekly releases will have the build date and last commit hash in their version number and zip name. Going forward, development version numbers will end in `-pre`, meaning that release versions will have to have their numbers changed for the one commit they get to be built from.
