### ISSUE TITLE
Default -t to modified

### ISSUE THREAD

**Issue by mqudsi** [ogham/exa#284]
[For compatibility with ls](http://man7.org/linux/man-pages/man1/ls.1.html), change `-t` from "optional flag with required value" to "optional flag with optional value" defaulting to modification date.

**Comment by mqudsi** [comment]
So this is apparently less straightforward than I had realized. I thought `--modified` sorts by modification date, but that only sets the behavior of the timestamp column.

How insane would it be for `exa -t` to be interpreted as `exa -s modified` in the name of ls compatibility? This doesn't clash with anything or break backwards compatibility with previous exa syntax, but it would be odd.

**Comment by ogham** [comment]
I did some work on this last night before I saw your second message.

Unfortunately, there's no way to have an optional argument in exa: either it always takes a value or it always doesn't. This is because the options parser allows you to drop the equals for single-letter options. If you ran:

    $ exa -ltr

Then it'll parse it like this instead, because `-t` takes a value:

    $ exa -l -t=r

So what exa now does is try to detect this case (by looking at the error messages) and guess which command you intended to run, based on what `ls` would do:


It only works for those two examples, but it's *something*.

**Comment by mqudsi** [comment]
Perhaps it would be best to add a --legacy flag to exa with ls-compatible flags. Then users could alias `ls` to `exa --legacy` and that would make everyone happy.

**Comment by ogham** [comment]
If I did that, I'd check the name of the running program to see if it's `ls`. This is similar to how old editions of `true` and `false` used to work: they were the same binary that checked itself to see what it should return (IIRC, anyway)

**Comment by ogham** [comment]
Anyway, exa and ls are very similar, so subsuming all of ls's functionality isn't too far-fetched an idea!

**Comment by andrew-lee-metaswitch** [comment]
The [release notes](https://github.com/ogham/exa/releases/tag/v0.10.0) suggest this is fixed, but that's not my reading of the [associated commit message](https://github.com/ogham/exa/commit/36cf5df044cea9f89bb9569cb6a42f072c12fdea ).

**Comment by ariasuni** [comment]
Yep, it’s an error that this issue was closed. But it’s tracked at #519 anyway, so let’s keep this one closed.
