### ISSUE TITLE
What is the yellow and underline for a file?

### ISSUE THREAD

**Issue by facenord-sud** [ogham/exa#29]
When we do `exa` in the directory of exa we have an output something like this:
![capture d ecran 2015-02-23 a 15 18 12](https://cloud.githubusercontent.com/assets/3266198/6329291/38189b94-bb6f-11e4-95d6-d9d38482f13d.png)

why the files README.md and Cargo.toml are in yellow and underline?

**Comment by ogham** [comment]
They're meant to be 'important files', including READMEs and build files, so the first time you enter a directory full of source code, you can immediately see which command you need to build it. See here for the list of names: https://github.com/ogham/exa/blob/master/src/filetype.rs#L50

There aren't really many there, because those were all I could think of!

**Comment by rverton** [comment]
Is there a way to deactivate this highlighting for important files?

**Comment by eggbean** [comment]
You can override exa's builtin styles using `LS_COLORS` or `EXACOLORS` variables for `.md` files or whatever.

eg.  `EXA_COLORS="*.md=38;5;121:*.log=38;5;248"`

https://github.com/ogham/exa/blob/master/man/exa_colors.5.md

**Comment by rverton** [comment]
I guess I have to do this for every 'important' extension then?

**Comment by eggbean** [comment]
Yes. Personally, I use `EXA_COLORS` just for the styling of exa elements and for file colours I use a dir_colors file which I based on some other one and added to over the years, which I then make into the `LS_COLORS` variable with `eval "$(dircolors -b ~/.dotfiles/path/to/dir_colors)"`

It's the same as with `ls`.

https://wiki.archlinux.org/title/Color_output_in_console#ls
