### ISSUE TITLE
Incompatible argument: -t

### ISSUE THREAD

**Issue by nedludd** [ogham/exa#294]
`ls -lrt` give you a sorted list with the oldest file last.

The same arguments in `exa` produces this:
```
$ exa -lrt
Argument to option 't' missing.
```

What `exa` arguments will produce the same result?

**Comment by dieggsy** [comment]
I believe you want `exa -lrs modified` or `exa -lr --sort=modified`

**Comment by nedludd** [comment]
OK, gotta retrain the muscle memory then ;-)

**Comment by ogham** [comment]
In #284 (out soon) I added a hint for this case, since it's such a common ls command. The hint looks like this, and refers to `newest`, which is `modified` backwards:

![Pasted Image 1.tiff](https://shipusercontent.com/1a1f476d9923ab976268889c565c64eb/Pasted%20Image%201.tiff)

(ignore that it's called `dexa`, that's an alias)

**Comment by smurfendrek123** [comment]
Will there be any improvement to this, or do i just have to alias exa -ltr to exa -ls modified, since I use the command quite a bit.

Also why is the sorting order reversed of ls -lt compared to exa -ls modified? with the ls command putting the newest items at the top, and the exa command putting the newest items at the bottom?

**Comment by Frederik-Baetens** [comment]
Now you can do exa -lsnew and exa -lsold and that works pretty well i find

**Comment by RandomErrorMessage** [comment]
Whatever, I'll be going back to standard ls. There's no need to break everyone's pre-existing workflow, and force people to switch between syntax while on different systems where exa is not installed. Expect this to be a common and repeated request by many individuals. I've seen no one explain why compatibility must be broken.

Good luck with your project, everyone.

**Comment by Frederik-Baetens** [comment]
While i will be sticking with exa i'm also curious about the design decisions. Mixing single letter arguments and words, like we do here with l and new is quite novel to me.
