### ISSUE TITLE
Feature Request: filter by filename without piping to grep

### ISSUE THREAD

**Issue by snoblenet** [ogham/exa#296]
I'd love exa to have the ability to filter by filename without piping to grep, as when you pipe to grep you have to disable colour codes as per my `zsh` function:

```
ex() {
  if [ -n "$1" ]; then
    exa -aBghlu | grep -e "$1\w*$"
  else
    exa -aBghlu --sort=accessed --color=always | less -R
  fi
}

```

**Comment by ogham** [comment]
Hey, sorry for the late reply.

exa does have an `--ignore-glob` option, but if I'm reading this right, you're looking to *include* files, rather than *exclude* them, right? If so, the easiest thing to do would be to do would be to just use the shell to glob the filenames, such as `exa *$1*`. (I think that would work with zsh.)

It might be possible to add an option that's the opposite of `--ignore-glob`, such as `--only-glob` or something, but I'm not sure how that would interact with `--recurse`.

**Comment by snoblenet** [comment]
Thanks. I settled on this:
```
list() {
  exa *$1*(D) -aBghlu --sort=accessed --color=always | less -R
  echo "$(PWD)"
}
```
The `(D)` is to include dotfiles.

**Comment by ogham** [comment]
Glad you found something that works. Is `(D)` a zshism? It's pretty ungooglable

**Comment by snoblenet** [comment]
It is: http://zsh.sourceforge.net/Doc/Release/Expansion.html#Glob-Qualifiers

**Comment by borekb** [comment]
By any chance, did exa gain native feature for include files since this issues was created? It's something I've wanted in `ls` in the past but skimming through exa's manunal, I don't think it supports either. But maybe I'm wrong?. (I'd prefer a built-in feature rather than relying on shell expansion.)
