### ISSUE TITLE
Color scheme for light terminals

### ISSUE THREAD

**Issue by ayosec** [ogham/exa#30]
When the background is white (or any light color), the output is hard to read.

![light](https://cloud.githubusercontent.com/assets/37484/6330936/2286c1a2-bb74-11e4-98b7-35e98e3a3502.png)

**Comment by ogham** [comment]
Usually you can set the colours in your terminal emulator so they work better with a light background. exa just uses the colours that you define there.

**Comment by ayosec** [comment]
Hi @ogham. Thanks for the response.

> Usually you can set the colours in your terminal emulator so they work better with a light background. exa just uses the colours that you define there.

The configured color is used for a dark background. If I select a darker yellow, it will look worse when another application changes the background on some characters.

Most programs provide a way to change the color scheme. Some examples:

* Vim has the option `:set background=...`, which can be `light` or `dark`.
  * It [tries to guess](https://github.com/neovim/neovim/blob/72cf89bce8e4230dbc161dc5606f48ef9884ba70/src/option.c#L2402-L2427) the value from the environemnt, and defaults to `light`.
  * You can change the scheme with `:color`, and it is adapted using the `background` value.
* [Htop](https://packages.debian.org/sid/htop) has [multiple schemes](https://cloud.githubusercontent.com/assets/37484/6339190/1919325c-bbac-11e4-8b4d-1c7bfd79761d.png) available in the setup options.
* [The Silver Searcher](http://geoff.greer.fm/ag/) can be configured using command line options. I use [a bash alias](https://gist.github.com/ayosec/dad37df3198852ab5388) to set my custom color scheme.

**Comment by ogham** [comment]
I'm sorry, I think I'm missing something here.

On the one hand, I can see that the bold colours in your screenshot *are* hard to read on a bright white background. On the other hand, all exa can do is use the sixteen colours specified in your terminal emulator - it should be a safe assumption that the user has configured their terminal so that all the default colours are readable. By making the bold colours darker, this will work for all programs, not just exa.

Here's what I see when I test with Solarized Light:

![screen shot 2015-02-24 at 13 56 08](https://cloud.githubusercontent.com/assets/503760/6350563/ecdc3924-bc2c-11e4-80b0-036459081dbd.png)

IIRC, it's not possible to set the background colour to be a bold colour, just a normal one, so any background colours on a light background are going to look dark anyway. (I tend to avoid setting the background colour anywhere, as I think it looks ugly no matter what the theme.)

**Comment by ayosec** [comment]
> all exa can do is use the sixteen colours specified in your terminal emulator

Actually, you can skip the terminal configuration using an explicit RGB value.

Most (all?) modern terminals have support for the 256 color mode, where the code is defined by `16 + 36 * r + 6 * g + b`, where `r`, `g`, and `b` are between `0` and `5`.

[This example program](https://gist.github.com/ayosec/16fed685f837f5b4596d) generates the following output:

![almost-256-colors](https://cloud.githubusercontent.com/assets/37484/6354800/c87bc762-bc49-11e4-9a5e-5a5f8f91227b.png)


> By making the bold colours darker, this will work for all programs, not just exa.

Only if the programs are using the default background. Many programs set their own background to avoid issues with the color scheme of the terminal.

Anyway, I can understand that this is not a priority. It will be cool if, in the future, the color scheme can be configured in some way. I like the approach of `ls`, using a `$LS_COLORS` variable generated by `dircolors` ([see `dir_colors(5)`](http://linux.die.net/man/5/dir_colors)).

I'm closing this issue. It can be reopened if more people are interested in a configurable color scheme.

**Comment by imiric** [comment]
Sorry for the "+1" comment, but the ability to customize the color scheme just for exa would be nice to have. Thanks for your work!

**Comment by ogham** [comment]
Just an update: although the colour schemes are not fully customisable yet, the colours themselves are now all set in the same place (in `colours.rs`) following commit bc844a3843cdc56630cf87c8f3ba1f2d6aa4152f.

**Comment by bobberb** [comment]
Can I add my support to a more $LS_COLORS config?
