### ISSUE TITLE
What color them are you using on the Exa marketing website? Love the colors.

### ISSUE THREAD

**Issue by derryl** [ogham/exa#323]
![image](https://user-images.githubusercontent.com/484537/33472534-a51d6d7a-d627-11e7-9924-d3f8ea27e17c.png)

**Comment by rdp** [comment]
mac terminal?

**Comment by ogham** [comment]
"Marketing website" made me smile! It was just something I threw together one day because I needed to prove I could do HTML and CSS for a job interview. (I didn't even get it.)

Anyway, the colours aren't *quite* the same as the [Tomorrow Night theme](https://github.com/chriskempson/tomorrow-theme), as I've tweaked them a little, but this is the closest you'll get. You'll find editor and terminal theme files there. If you really want the exact colours you'll find them in the site's CSS.
