### ISSUE TITLE
What's the best way to support exa development without knowing Rust?

### ISSUE THREAD

**Issue by naiveaiguy** [ogham/exa#334]
I love `exa` and I rely on it every day as part of my workflow. Last I checked the median times I ran it per day was ~100, which is insane. I don't even run `git` that often! (~20 - actually, the fact that `exa` has git options probably reduces this number significantly)

As such, I would love to support `exa` as much as I can, but I do not know Rust, so I'm not sure how I can contribute. What's the best way to do this, monetarily or otherwise?

**Comment by notramo** [comment]
I think,  the most easy way is spreading the word about it.
For example: when I open an issue in a repo, and it needs a sample shell code snippet, I use my favourite tools in these example codes.

**Comment by ogham** [comment]
Your comment is from December and I’m replying in May... this makes me a little hesitant to accept money or something for it when I know I could be doing a better job maintaining it.

So the second-best way to support exa is to spread the word about it. The *first*-best way is to let me know you like it, because it’s comments like yours that keep me going!=

(I run it hundreds of times per day too)
