### ISSUE TITLE
Many useful ANSI codes do not work with exa

### ISSUE THREAD

**Issue by s-hamann** [ogham/exa#347]
> Unlike some versions of ls, the given ANSI values must be valid colour codes: exa won't just print out whichever characters are given.  The codes accepted by exa are [very basic codes]

I'm sure there is a reasoning behind this, but I fail to understand it. The way it is, exa misses out on lots of useful ANSI codes, some of which I actually use in my `$LS_COLORS`.
An example is missing support for 24 bit colours, as mentioned in #339. But there is so much more. Here's a non-exhaustive list of code I miss (and that are actually supported by my terminal). Others may make a case for even more codes.
* faint text (`2`)
* italics (`3`)
* crossed-out (`9`)
* background-colours (`40`-`47`)
* non-bold bright colours (`90`-`97`)
* bright background colours (`100`-`107`)
* 256 colour background colours (`48;5;nnn`)
* 24 bit colours (`38;2;rrr:ggg:bbb`)
* 24 bit background colours (`48;2;rrr:ggg:bbb`)

Could this be implemented? Does that need to be implemented at all, or is it simply a matter of dropping that filter for known ANSI codes and handing the responsibility for picking correct codes to the user?

**Comment by BrendanLeber** [comment]
Agreed.  exa is nice but without this the output is unreadable on my system.

**Comment by AntonioND** [comment]
I use the codes between 90-107 for `ls`. Even if I switched to 256, it doesn't seem like it would make any difference...

I'm using `LS_COLORS` so that the output of `ls` and the colors used for completion in `zsh` are the same. In `exa`, with this behaviour, many files look plain white.

Can't you just pass the sequences to the output blindly, or even ignore `LS_COLORS`? It would be better to just pass the sequences, but even ignoring `LS_COLORS` completely would be better.

**Comment by ogham** [comment]
Hi all, sorry for the late reply on this issue.

> I'm sure there is a reasoning behind this, but I fail to understand it.

There's no technical reason why adding these extra codes is impossible — it's merely a matter of adding them, which I'm certainly willing to do.

What's annoying is the way exa's theming works at the moment. Instead of blindly copying the bytes like what was suggested, it parses the ANSI codes into a list of attributes, and then redundantly _un_-parses them to print them out again. This means that exa needs to know what a code means in order to display it.

I'm kind of hoping that by adding the missing styles (italic, faint, strikethrough, etc) and 256-bit colour, I'll have covered enough of the use cases here.

**Comment by ogham** [comment]
> 256-bit colour

heh, you know what I mean

**Comment by ogham** [comment]
Having considered it a bit more, I think the eventual solution _should_ be to stop trying to parse the ANSI codes at all, and instead just find a way to copy the strings into the output without understanding them. This attitude mostly comes from seeing how fiddly the 24-bit colour codes are to parse.

For now, I’ve added support for most of the ones people were missing:

<img width="320" alt="screen shot 2018-10-08 at 03 58 10" src="https://user-images.githubusercontent.com/503760/46590906-dadf7d00-caae-11e8-89ed-6c7d397f03e4.png">

**Comment by mje-nz** [comment]
For anyone else who's here because your LS_COLORS doesn't work with exa, here's which of OP's codes do work:

- [x] faint text (2)
- [x] italics (3)
- [x] crossed-out (9)
- [x] background-colours (40-47)
- [ ] non-bold bright colours (90-97)
- [ ] bright background colours (100-107)
- [ ] 256 colour background colours (48;5;nnn)
- [ ] 24 bit colours (38;2;rrr:ggg:bbb)
- [ ] 24 bit background colours (48;2;rrr:ggg:bbb)

See [here](https://github.com/ogham/exa/blob/39c8c67bf6237076b24915851f908d6da13c04b7/src/theme/lsc.rs#L98) for the full list.

I was using 90 for grey, but 2 for dim is fine too.

**Comment by roshal** [comment]
@ogham

there is still no support for non-bold bright colours 90-97 and bright background colours 100-107

please reopen this issue

**Comment by mafrosis** [comment]
@ogham How hard do you think it will be to implement a pass-through option for the colour codes? I would like 24-bit colour 🏳️‍🌈
