### ISSUE TITLE
List compressed files

### ISSUE THREAD

**Issue by janderholm** [ogham/exa#354]
Ripgrep just got the ability to search in compressed files. This got me thinking, I think it would be very useful if exa could be used to list compressed files.

**Comment by ogham** [comment]
This is an interesting feature that I have absolutely no idea how to implement!

I’m going to leave this issue open in case it happens one day.

**Comment by rianadon** [comment]
This is an interesting feature and I'd love to draft an initial version of it. However, this is a radical difference in behavior of `ls`, so a couple philosophical questions:

1. Having multiple tools (`unzip`, `tar`, etc) to each list the files of a specific type of compressed folder seems more in line with the Unix philosophy than a single tool (`exa` after this issue is resolved) that can list any type of compressed folder.
Is the advantage of making `exa x.tar` or `exa -z x.tar` (where `-z` is a switch to handle compressed folders similar how ripgrep has a `-z` switch for compressed files) worth the cost of duplicating what `unzip`, `tar`, etc already do?

2. Say the answer to question 1 is no. `exa -T` could still support listing the contents of compressed folders if the compressed folder is nested under another folder (since this is not replicating the functionality of `unzip and `tar). Should this be default or non-default behavior?

**Comment by mschilli87** [comment]
@rianadon:

Not sure if I got point 2 but since you mention the UNIX philosophy in point 1, I'm sure there is a way to do that already (*e.g.* using `find [...] -exec [...]`). If you give a concrete example, I can get more specific, too. :wink:

Also, why not simply *use* the existing tools (`unzip`, `tar`, etc.) from within `exa` instead of duplicating what they do? If `exa` sees the `-z` flag and it hits an archive file of a type it knows about and knows how to list, list it like a directory instead.

**Comment by rianadon** [comment]
@mschilli87 thanks for the feedback!

I'm sure there is a way to replicate the behavior of `exa -T` with a bash script that also lists compressed directories :grin:. However it's probably fairly long to either replicate exa's formatting or to feed information into exa for formatting. I've edited point 2 to be slightly more clear.

As for using existing tools, there's a tradeoff between using pure Rust libraries like [tar](https://github.com/alexcrichton/tar-rs) versus the command. We'd either be significantly increasing the size of the exa binary or doing some command line parsing. Do you have advice?

**Comment by ogham** [comment]
Since this issue was raised, I've started being suspicious of the amount of features exa is accumulating. I don't think adding this feature is worth the cost in complexity.
