### ISSUE TITLE
Offer official aliases

### ISSUE THREAD

**Issue by clarfonthey** [ogham/exa#374]
As discussed in #195, a lot of people use aliases for exa similar to those for `ls`. It'd be nice if we could offer official aliases for these (similar to `ls`, `ll`, `la`, and `tree`) so that users have access to these aliases without having to set up anything different in their shells.

Personally, I vote for `xs`, `xl`, `xa`, and maybe `xt`; most people seem to prefer these.

What makes the most sense is to simply parse the currently-skipped first argument in `args_os()`, using that to determine which alias is in use. That way, people can simply symlink `exa` to aliases with these names to make them work, and it allows distributing a single binary while still reaping these benefits.

This would also be a huge benefit over `ls`, as most people create aliases for `ll` and `la` when `ls` itself does not officially support these.

**Comment by ogham** [comment]
(I mixed up the labels because I misunderstood the request)

There’s some discussion over in #332 about ‘ls mode’, where we’d do one of the things you suggest: see if the binary is being invoked as `ls`, rather than `exa`, and offer a different command-line interface if it does.

This is a similar feature, except it only has to support exa’s *current* command-line interface, rather than inventing a new one!

However I’m not sure about this feature’s scope. I haven’t run a poll of how often these aliases are used (maybe I should); if it supports `xl`, no doubt there’d be a feature request to support `exal` or something similar immediately after. And if you want to have shell aliases, wouldn’t it be the same amount of work creating the symlink as it would creating the alias?

**Comment by hyiltiz** [comment]
x is harder to type than two characters ls.

**Comment by clarfonthey** [comment]
Closing this since it's unlikely to be resolved here, and better suited for the eza fork.
