### ISSUE TITLE
read from stdin

### ISSUE THREAD

**Issue by flip111** [ogham/exa#394]
Sometimes i want to use another program to supply the files and use `ls` to give more information about the file. Could reading from stdin be added to exa?

**Comment by flip111** [comment]
Sorry i was mistaken apparently `ls` also needs xargs to do this

**Comment by ogham** [comment]
Yeah, you can use `xargs` to do this:

<img width="415" alt="screen shot 2018-06-05 at 16 05 36" src="https://user-images.githubusercontent.com/503760/40984674-5a556180-68da-11e8-9095-f6cde7e45c4e.png">

I’d like to keep to the Unix Philosophy here, and recommend just using `xargs` rather than trying to duplicate all its functionality and quirks. Once you’re used to using it, you can use it with _any_ command, not just exa!

**Comment by flip111** [comment]
I understand you
