### ISSUE TITLE
Color auto does not work in screen or tmux session

### ISSUE THREAD

**Issue by zlynx** [ogham/exa#400]
I wondered why exa was all boring looking on a Talos II PowerPC system and realized that it doesn't seem to auto-detect that it should use color.

Forcing color does work. And the `ls` command uses color automatically. So it is something with exa.

**Comment by Don42** [comment]
Hi,
What is the **TERM** variable in your screen and tmux set to?
This would help reproduce the issue.

**Comment by zlynx** [comment]
I guess I did leave out a lot of detail.

The system is a Talos II PowerPC running Fedora 28 in little-endian mode. It actually appears to have nothing to do with tmux because even without it, exa has no automatic color.

TERM xterm, exa = no color
TERM screen, exa = no color
TERM xterm, exa --color=always = color
TERM screen, exa --color=always = color

exa-0.8.0-4.fc28.ppc64le

On an x86_64 system the same version of exa, exa-0.8.0-4.fc28.x86_64, produces color in TERM xterm or screen.

**Comment by ogham** [comment]
Hi, thanks for reporting this. Sorry for the late reply.

Unfortunately I’m completely out of Talos II PowerPC computers to test on, mostly because I only found out they existed a minute ago, so I’m not able to reproduce this myself.

You’re correct in thinking that system call has something to do with it. If you don’t pass `--color=always`, exa checks to see if you’re running in a terminal, and uses colour if you are and switches it off if you’re not. It does this check by using the `term_size` crate, which, as you’ve found in strace, [uses `TIOCGWINSZ` under Unix](https://github.com/clap-rs/term_size-rs/blob/644f28c3a8811e56edcf42036b5e754dbb24a0d7/src/platform/unix.rs). There’s nothing in there for PowerPC, but based on the `0x54, 0x13` present in the strace output, it looks like it’s still using 0x5413.

Are you saying it should be flipped around, to be `0x1354` instead? If so, I could build you a one-off version to see if it works.

**Comment by q66** [comment]
It's not an endian issue, instead it should be using the `0x40087468` value on powerpc linux like on the BSDs and macOS: https://github.com/clap-rs/term_size-rs/blob/644f28c3a8811e56edcf42036b5e754dbb24a0d7/src/platform/unix.rs#L9

This simple test program:

```
#include <stdio.h>
#include <asm/termios.h>

int main() {
    printf("%X\n", TIOCGWINSZ);
    return 0;
}
```

outputs `40087468` on my `ppc64le` Linux system.

But... why check it like this? Is `isatty` not good enough? That's the typical standard way to test if you're running an interactive terminal.

**Comment by ariasuni** [comment]
From [`term_size`’s README.md](https://github.com/clap-rs/term_size-rs):

> # Maintenance status 
>
> **This crate is no longer maintained**. It works fine, but the maintainers don't have time and willingness 
> to work on it or review future PRs anymore.
>
> Consider using [`terminal_size`](https://github.com/eminence/terminal-size/) instead.

`terminal_size` uses `TIOCGWINSZ` from libc. [source](https://github.com/eminence/terminal-size/blob/68753331337bbf61f19d60511811fc981e67a528/src/unix.rs#L31).

libc itself seems to use `40087468` for all powerpc variants:
- [musl, 32-bit](https://github.com/rust-lang/libc/blob/4d0cd9ae1034582a49c1cc8532cb9591ef0ef179/src/unix/linux_like/linux/musl/b32/powerpc.rs#L431)
- [musl, 64-bit](https://github.com/rust-lang/libc/blob/4d0cd9ae1034582a49c1cc8532cb9591ef0ef179/src/unix/linux_like/linux/musl/b64/powerpc64.rs#L638)
- [GNU libc, 32-bit](https://github.com/rust-lang/libc/blob/ac494b16a5802b7fdd5fd4fca327c867cdf7dbaa/src/unix/linux_like/linux/gnu/b32/powerpc.rs#L473)
- [GNU libc, 64-bit](https://github.com/rust-lang/libc/blob/ac494b16a5802b7fdd5fd4fca327c867cdf7dbaa/src/unix/linux_like/linux/gnu/b64/powerpc64/mod.rs#L626)

So using `terminal_size` should fix this.
