### ISSUE TITLE
--grid --tree --long disables --long

### ISSUE THREAD

**Issue by HaleTom** [ogham/exa#407]
Using options `--grid --tree --long` disables `--long` output.

It seems that `--grid` is disabled if `--tree` is enabled. Document this?

Perhaps disable `--grid` *only if* the `--tree` option would print any tree (ie if there are subdirectories)?

**Comment by ogham** [comment]
This was an unexpected side-effect of how options are parsed, rather than intended functionality, so I changed it to make it intended (not merged yet). It'll go out in the next release.

The change makes exa evaluate view modes right-to-left, like it does with other options. `--grid --tree --long` will parse as `--tree --long`, because `--long` is the right-most view mode argument, and `--tree` is present. Similarly, `--oneline --grid` will parse as `--grid`.
