### ISSUE TITLE
"--" is misinterpreted

### ISSUE THREAD

**Issue by xyproto** [ogham/exa#424]
Hi,

Thanks for creating `exa`, I use it daily, instead of `ls`.

One issue I recently encountered was this:

```
$ touch a.#a-tu.log
$ /usr/bin/ls -ralt -- *-tu*
-rw-r----- 1 alexander users 0 okt.  11 09:36 a.#a-tu.log
$ /usr/bin/exa -ralt -- *-tu*
Option --time (-t) has no "--" setting (choices: modified, accessed, created)
```
Regardless that `exa` is not necessarily a drop-in replacement for ls when it comes to flags/options, I would expect that `exa` would not intepret anything after `--` (or `--` itself) as options.

This is for `exa v0.8.0`.

Cheers!

**Comment by Phidica** [comment]
This is because the `-t` option in exa requires an argument: either "modified", "accessed", or "created". In ls, the `-t` option does not require an argument because it is equivalent to exa's `-t modified`. If you remove the `t` from your exa example I think you'll find that the end of options parameter `--` is being treated correctly by exa

**Comment by mineo** [comment]
In this case, exa's behaviour of treating `--` as the required argument of an option is what `ls` does as well:

```
↪ LC_ALL=en_US.utf8 =ls --block-size -- *
/usr/bin/ls: invalid --block-size argument '--'
```

**Comment by xyproto** [comment]
OK. Thanks for the info!
