### ISSUE TITLE
[Feature Request] : Ignore all arguments for alias command

### ISSUE THREAD

**Issue by Dentrax** [ogham/exa#449]
I am usually using Exa with an `alias` command that called from my `.zshrc` config.

`alias ls="exa --git --group-directories-first -lahGFm"`

In most of the time I call the command that way. But sometimes we have to be quick to see important things. We don't want our attention to be distributed with colors and overmuch details. Like as in the above `alias` example I normally use. (I don't want to change it, I like it that way)

In the cases that i told above, I use the normal `ls` command. To not call the `alias` code, here's how I use it:

`$ /usr/bin/ls .`

If there was a high-priority argument that ignored all the other arguments, It would be so life-saver. Like this:

`ls`: My `alias` command for Exa

`$ ls -i`

...which means:

`$ exa --git --group-directories-first -lahGFm --ignore-all`

**P.S:** `--ignore-all` command was processed first than other arguments.

Using the `-i (--ignore-all)` argument, we have ignored all the others arguments. (In this case, `--git --group-directories-first -lahGFm` arguments ignored)

_Thanks in advance_

> Don't forget to mention your different suggestions and ideas. :)

**Comment by qubidt** [comment]
I use zsh + exa aliases as well. If you want to just call `ls`, ignoring the alias, why not just:
```
$ \ls
```
?

If i really want to call exa without the parameters in the alias, I just use `exa` instead of my alias (`l`)

**Comment by alivefromupstairs** [comment]
@Dentrax Close.

**Comment by ogham** [comment]
I alias it as well! Mine look like this, though:

```fish
    alias ll 'exa --long --git --header'
    alias ls 'exa'
```

I think this is something that should be done by the shell, rather than by exa itself. As mentioned above, you can use the backslash in zsh (I use `command` in fish) to get the original behaviour back. You could even write a shell function to detect the use of `--ignore-all` and splice `$@` if you really wanted the feature. From what I've seen of other people's setups, the Aliasing Way seems to be to use two aliases, rather than one that can be overridden.

Also, it's not a common feature: I don't know of other tools that have such a flag, whereas the only existing "meta-argument" (`--` to separate flags from files) is well-supported.
