### ISSUE TITLE
argument D is not working

### ISSUE THREAD

**Issue by abbychau** [ogham/exa#456]
```
Abbys-MacBook-Pro:backoffice abby$ exa -D
Unknown argument -D
Abbys-MacBook-Pro:backoffice abby$ exa -T --only-dirs
Unknown argument --only-dirs
```

**Comment by hagnerd** [comment]
Running into this as well

**Comment by Don42** [comment]
Mh, ok. This is quite weird. I'm pretty sure my changes worked before the pull request.
My old feature branch still works, but current master doesn't. I'll take a look in the next few days.

Thanks for reporting this.

**Comment by abbychau** [comment]
```
~/exa master
❯ ./target/debug/exa
build.rs    contrib   Makefile         src          xtests
Cargo.lock  devtools  README.md        target       
Cargo.toml  LICENCE   screenshots.png  Vagrantfile  

~/exa master
❯ ./target/debug/exa -D
contrib  devtools  src  target  xtests

~/exa master
❯ 
```

the master branch is working too. Did you publish a wrong one?

**Comment by Don42** [comment]
Which version didn't work? This feature did not exist when the last release was made.

**Comment by abbychau** [comment]
> Which version didn't work? This feature did not exist when the last release was made.
> 
> Current master ([058b4a5](https://github.com/ogham/exa/commit/058b4a57bdb1e25cbdacc0fbd1eefc09bc5f1e95)) works for me. I'm assuming this is just an issue with the release being very old and not including features added in the last year.

The current master works for me too, which as i mentioned above. 

However, what you published to `cargo` or `brew` is opaque to us. You can probably try a `brew install exa` or `cargo install exa` and have a taste. Maybe you can try to republish it.

**Comment by Don42** [comment]
@abbychau I think you're mistaking me for @ogham.
As I mentioned, the released versions here and on crates.io (and probably on brew)
are about a year and a half old and do not contain this feature.

**Comment by abbychau** [comment]
Can you update them?

**Comment by Don42** [comment]
No, only @ogham can do that.

**Comment by ToonSpin** [comment]
I'm noticing that this issue isn't assigned to @ogham, so I can only assume nobody is going to push a new version to the Homebrew repo. The "bus factor" here seems to be pretty big if only ogham has the means to do this, at least where Homebrew is concerned.

I am just learning about Exa, and I really like it but can't in good conscience recommend it to my coworkers, most of whom use a Mac, if the Homebrew repo is not updated for a year and a half and that doesn't seem to faze anybody in the slightest.

Have there been any security fixes in the mean time?

I'm sorry to say I have no solution for this issue because I don't have a Mac at home and have no time to help maintaining an open source project in my spare time right now, but I do feel that someone should either take exa out of Homebrew or actually maintain it.

Not being familiar with Homebrew, isn't this simply another step to add to the release process? Or is it more complicated than that?

**Comment by ToonSpin** [comment]
I've deleted my last comment because it is not relevant - there have been no new releases in the last year and a half.

Time for a new release? :)

**Comment by ariasuni** [comment]
exa 0.9.0 has been published on Jul 15 2019, and I can confirm it works, so closing this.
