### ISSUE TITLE
Should respect terminfo.

### ISSUE THREAD

**Issue by vlad-shatskyi** [ogham/exa#52]
Currently, for example, `set_a_foreground` is always an ASCI sequence appropriate for `xterm-color`, even if my terminfo entry has a different one.

To verify:

``` bash
# Create a terminal info copy. 
infocmp -L xterm-256color > my-term.ti
# Change its name and color attribute.
sed -i.bak 's/xterm-256color|xterm with 256 colors/my-term|My Terminal/' my-term.ti
sed -i.bak -E 's/([[:space:]]+set_a_foreground=).*/\1smth/' my-term.ti
# Compile it
tic my-term.ti
# Set the current terminal emulator to use the newly compiled terminfo.
export TERM=my-term

exa
```

It must print `smth` instead of colors. If you replace `exa` in the last command with, say, `vim`, you'll see the difference. I'd recommend you to take a look at the `tput` command.

**Comment by ogham** [comment]
Yeah, I should probably start using the built-in `term` crate now it supports such things.

**Comment by ogham** [comment]
Oops, didn't mean to close

**Comment by ogham** [comment]
Hey @shockone, you seem like you know a thing about terminfo! Could you help?

I'm trying to change `rust-ansi-term` so it uses the terminfo settings from the `term` crate. (I can't use the `term` crate's interface directly, as it doesn't support 256 colours, or difference checking). But there doesn't seem to be a command to set more than one attribute at a time, such as setting the foreground *and* background, or the foreground and underline. Do you know if this is possible without writing the codes manually (which is what I'm currently doing?)

For example, in https://github.com/ogham/rust-ansi-term/blob/master/src/ansi_term.rs#L481, I have one code with six components that sets both the foreground and background. This is accepted by all the terminals I've tried it on, but I can't actually find it in the terminfo standard!

**Comment by shockone** [comment]
Hi, @ogham. I don't know that much, but I'll try to help.

Your example line contains two escape codes: `\x1B[48;5;200;38;5;100m` and `\x1B[0m`. There is some `hi` in between, I'm not sure what it is and I wasn't able to find any description of these characters. 

So, the first one is `extended set background color`. In `terminfo` it's `set_a_background`. You can find more information [here](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes) in the column `CSI n m` and also take a look on CGR code 48 on the same page; it describes what exactly the numbers mean. The second one is `reset all attributes`. 

By the way, CGR 48 is how you support 256 colors. Terminals have 8 user defined colors, which means you can change the notion of red, for example. All the rest are not changeable and are set using this extended command.

It's strange that your command first sets the background color and then resets all the attributes including this color back. Maybe `hi` is something like a placeholder for text so that we have it with a background color and then reset back.

**Comment by shockone** [comment]
Ah, I got it. It's a test, and `hi` is a welcoming message. :). So, you can't change two attributes with a single command. Think of the escape sequences as of something that changes terminal's internal state. We send a sequence to set a foreground, and all the text we'll send it from now on will be printed in that color. Until we reset it. 

You just need to send two ANSI codes: set background and set foreground. Does it answer your question?

**Comment by shockone** [comment]
I was wrong. You can definitely set two attributes with one sequence, like [here](https://github.com/ogham/rust-ansi-term/blob/master/src/ansi_term.rs#L478).

If you use `tput`, `"\x1B[1;4;47;36m` will become "\x1B[1` `\x1B[4``\x1B[47;36m`, right? I guess you could somehow detect and merge the consecutive codes into one.

**Comment by ogham** [comment]
Yeah, that's it! You're right that the effect of having two codes rather than just one would be the same, but I'd like to both have support for different types of terminals (with terminfo) and output the minimum number of characters necessary.

**Comment by shockone** [comment]
I haven't found how to do it, but I'll let you know if I will. 
You don't like the idea of merging them in the library, right? For example, having an API like (abstract syntax, I haven't learnt Rust yet) 

```
"some test".ansi(background: Color.Black, foreground: Color.Red, decoration: [Bold, Underlined])
```

it would be really easy to generate the codes and concatenate them into one sequence.

**Comment by ogham** [comment]
Ok, thank you. I'm going to try asking on StackOverflow. If it can't be done, I'll just use multiple commands as you suggest.

**Comment by ogham** [comment]
I asked [Is it possible to change the foreground and background colour at the same time with terminfo?](http://stackoverflow.com/questions/30107933/is-it-possible-to-change-the-foreground-and-background-colour-at-the-same-time-w) and was told that it isn't. Oh well. I'm just going to use multiple commands.

**Comment by rpdelaney** [comment]
Will this feature cause exa to apply `dircolors` as well?

**Comment by ogham** [comment]
Having generally surveyed the command-line landscape since this question was asked six years ago, I've seen _so much_ ANSI hardcoding and terminfo ignoring that I'm going to keep exa producing ANSI codes. exa has grown features that assume the ANSI featureset: things like the `EXA_COLORS` mechanism are based around the ANSI escape code format — and there are significant technological downsides to going through terminfo.

In 2019 I asked this question on Stack Exchange: [In 2019, is it safe to assume that all terminals understand ANSI escape codes?](https://unix.stackexchange.com/questions/548158/in-2019-is-it-safe-to-assume-that-all-terminals-understand-ansi-escape-codes) It got closed, of course, and while there were some arguments saying it's best to follow the standard, I didn't get answers from anybody who actually regularly used one. Since then, I have seen one person in the wild on the Internet who was frustrated at everything assuming ANSI... but only one.

(If you're a non-ANSI terminal user, please get in touch with me, because I'm interested in those use cases across my projects.)

**Comment by rpdelaney** [comment]
In fairness, the apparent dearth of folks complaining about terminals assuming ANSI might be the result of searching in English. Searches in other languages might bear more fruit. But I have no horse in this race.
