### ISSUE TITLE
--icons Spacing

### ISSUE THREAD

**Issue by macintacos** [ogham/exa#541]
The new `--icons` option is great, but one thing that's bothering me is the spacing for pretty much any file name that doesn't start with a small character (folders/files that start with dots actually look pretty fine).

Example: 

![](https://cl.ly/267b6ea8169d/Image%202019-07-20%20at%2017.28.33.png)

Maybe it's just me, but the icons are just a bit too close to the first character of the directory name, and it just makes things feel cramped. Any chance that this spacing could be manually adjusted perhaps?

**Comment by windware-h-ono** [comment]
I suppose it depends on the font used.

I use patched 'Sauce Code Pro' and it already has plenty of spacing.

![icons-spacing](https://user-images.githubusercontent.com/4352236/61636799-52df0280-acd1-11e9-8435-97072404191f.png)

Probably best as a configuration option `--icons-spacing` to specify 'pt' as a number?

**Comment by macintacos** [comment]
Yeah I’m not a fan of the smaller icons; I tried out those and some of them were illegible to me until I made the font point size comically large which was just not good for general use.

The option to space these out from the text would be good enough for me. Even if it’s just a literal “space” character (or maybe a character of my choice?) I’d be happy with that!

**Comment by Azumgi** [comment]
Yeah, putting a space inbetween sounds like the best solution. [colorls](https://github.com/athityakumar/colorls) does this by default and it looks pretty good. Here's a comparison:
![image](https://user-images.githubusercontent.com/35058624/61705620-ca06ac00-ad4e-11e9-8667-6713223c9cf2.png)

**Comment by lilyball** [comment]
There already is a literal space character between the icon and the filename. The problem is the icon is drawing effectively double-wide while occupying a single column.

For comparison, using a patched Menlo font in macOS Terminal.app:

![Screen Shot 2019-07-25 at 12 08 23 PM](https://user-images.githubusercontent.com/714/61901569-e7658280-aed4-11e9-9263-cfdfaebe7a6c.png)

It looks to me as though the icons in my screenshot are still basically double-wide, except Terminal.app is centering the icon on the column instead of left-aligning it. This means it overlaps half of the preceding space and half of the the succeeding space, and ends up looking decent.

And when looking at the Grid output, it's clear that adding an extra space after the icon would look really bad, as it would make the icon appear to be its own grid entry instead of associated with the file:

![Screen Shot 2019-07-25 at 12 14 59 PM](https://user-images.githubusercontent.com/714/61901953-d406e700-aed5-11e9-964b-909d6d69a56a.png)

**Comment by lilyball** [comment]
Which is to say, I have no objection to an `--icons-spacing` flag (though maybe it should just be a boolean flag `--extra-icon-spacing` instead of taking an argument?), but it should not be the default behavior.

**Comment by macintacos** [comment]
Ah; to be honest, I think the centering would work better for me instead of adjusting the spacing. Could you link to the patched font that you use?

If this issue is unique to iTerm, then that sucks; I won’t be switching back to Terminal.app for a good long time.

**Comment by lilyball** [comment]
NerdFonts doesn't have a download for Menlo directly, so I have to assume I patched this myself (I've been using it for years so I don't remember), but as the base font is owned by Apple I don't have the rights to distribute it. You should be able to run their Font Patcher Script on the copy of Menlo found on your system.

That said, I would encourage you to try this in Terminal.app, because I'm guessing the centering is special Terminal.app behavior when it encounters a character too wide for the column, because if it was font behavior then I would expect it to occur on all patched fonts, not just Menlo.

**Comment by macintacos** [comment]
FWIW, I just tried the Terminal.app and am seeing the same spacing compared to iTerm; there is no centering going on, as far as I can tell.

**Comment by Sherulez** [comment]
Speaking of the Nerds Fonts :

- "_[font family] Nerd Font Complete_" will have **non-Monospaced** ( variable-width ) icons
- "_[font family] Nerd Font Complete **Mono**_" will have **Monospaced** ( fixed-width ) icons

Of course Monospaced  icons will be "smaller" since they will share the same width as the letters.

For the record, powerlevel10k takes care of this problem during its configuration via this question :
![Capture](https://user-images.githubusercontent.com/25638207/75053758-1cb96980-54d2-11ea-91a0-1b1190d5e957.PNG)

If you say no here, 1 space will be added after each icons.

I look forward to this new flag :) (`--extra-icon-spacing`)

**Comment by macintacos** [comment]
I solved this by just setting these in iTerm, since you can specify non-ASCII characters differently from ASCII ones:

![image](https://user-images.githubusercontent.com/8128941/75084407-e7bb1000-54ed-11ea-90ff-a14598124bd3.png)

Hopefully this helps those that use iTerm 🙂

**Comment by ogham** [comment]
While testing icons with various fonts, I encountered both those that needed one space and those that needed two spaces. The aforementioned enviroment variable, `EXA_ICON_SPACING`, will do that (as of next release):

![Screenshot 2020-10-24 at 19 41 34](https://user-images.githubusercontent.com/503760/97091076-ee77c500-1630-11eb-9e87-b0e974bf787a.png)

(ignore the fact that all icons are question marks)

It's an environment variable because it's not something that will usually change between exa invocations. It's more of a global setting.

**Comment by vincentmader** [comment]
> I solved this by just setting these in iTerm, since you can specify non-ASCII characters differently from ASCII ones:
> 
> ![image](https://user-images.githubusercontent.com/8128941/75084407-e7bb1000-54ed-11ea-90ff-a14598124bd3.png)
> 
> Hopefully this helps those that use iTerm 🙂

Unfortunately, having different font sizes for ASCII / non-ASCII characters can visually break stuff in other places, e.g. the vim status-line here: 

<img width="166" alt="Screenshot 2022-10-23 at 12 56 45" src="https://user-images.githubusercontent.com/24686711/197388245-514e37e1-7aa4-40cf-aec4-5c94a68dcf55.png">

Would it be such a big deal to add a space after the icons? It would make exa look a lot more visually appealing in my opinion...

<img width="101" alt="Screenshot 2022-10-23 at 12 58 35" src="https://user-images.githubusercontent.com/24686711/197388298-369cda03-1030-4911-aed7-da628e22a835.png">

**Comment by macintacos** [comment]
This issue should probably be closed, since this seems to have been resolved with an environment variable in this commit: https://github.com/ogham/exa/commit/51be9f4c43e61bbea61e70e1459e494207d1d979
