### ISSUE TITLE
Style between icon and filename

### ISSUE THREAD

**Issue by grigorii-horos** [ogham/exa#561]
Now file look like this:
![Screenshot_20190804_020246](https://user-images.githubusercontent.com/4980269/62417604-1bbb0a80-b65c-11e9-839c-2b2659513641.png)

~You can see an unstyled space between icon and filename. I think that would be better if, after the icon, colors will not reset.~

**Comment by horosgrisa** [comment]
I thin that will be better to reverse colors for icon if filenam has background

![image](https://user-images.githubusercontent.com/4980269/62425256-bc074280-b6e1-11e9-8e58-a948c003b6bf.png)

**Comment by ogham** [comment]
I made a commit so that the icon colour uses the background colour before the foreground colour, if one is set. I think it looks nicer (exa v0.9.0, previous exa dev version, current exa dev version):

![Screenshot 2020-10-24 at 18 30 59](https://user-images.githubusercontent.com/503760/97088180-12cea400-1627-11eb-90bc-193216f6cc46.png)
