### ISSUE TITLE
"creation time is not available on this platform currently"

### ISSUE THREAD

**Issue by bobblkabb** [ogham/exa#576]
**exa -bghluUa** used to work now I'm getting an error message.
File manager (dolphin) shows creation time of files and folders.

exa 0.9 on openSUSE

**Comment by cyrinux** [comment]
Same for me on an updated archlinux with btrfs filesystem.
It was working well before.

**Comment by oscarcp** [comment]
Same here on arch linux, was working perfectly, now spits out "creation time is not available on this platform currently" in btrfs filesystems

**Comment by Lisible** [comment]
Same here, on ArchLinux with an ext4 filesystem.

**Comment by tsoernes** [comment]
Same on Fedora 30 with exa 0.9 on ext4

**Comment by roblav96** [comment]
Same here,
```
Ubuntu Server 19.10 (GNU/Linux 5.3.0-22-generic x86_64)
```
@ogham @ariasuni

**Comment by ariasuni** [comment]
Rust doesn’t know how to get the created time is on Linux. Now exa correctly reports an error instead of displaying a misleading time… See #457.

Support has been added recently with https://github.com/rust-lang/rust/pull/65094 but I think it’s not in any stable release yet. An exa executable produced by a next version of Rust will just work and display the created time, but for real this time.

**Comment by NightMachinary** [comment]
@ariasuni A better design choice would have been to print a warning on stderr, since this change is needlessly breaking working scripts.

**Comment by ariasuni** [comment]
I noticed the design wasn’t good so I vastly improved it in https://github.com/ogham/exa/pull/616.

**Comment by GitGangGuy** [comment]
@ariasuni What's the status on this? The rust PR got merged and I'm still receiving this error on Arch Linux with an ext4 file system, even though stat works perfectly fine.

**Comment by ariasuni** [comment]
A new version hasn’t been released after this PR got merged, so this is perfectly normal.
