### ISSUE TITLE
-Gl doesn't produce long listing with -T or when piped

### ISSUE THREAD

**Issue by j-tai** [ogham/exa#583]
Given `-Gl`, exa displays a long listing, but when `-T` is also given, or exa's output is piped, it does not:

```console
$ exa -Gl
.rw-r--r-- 0 jtai Sep 14 19:54 foo.txt
$ exa -Gl | cat
foo.txt
$ exa -GlT
.
└── foo.txt
```

**Comment by ogham** [comment]
This was also #407. I made a change (not merged yet) and left a comment over there explaining it. `exa -GlT` will now do the same thing as `exa --long --tree`, ignoring the `--grid` because it's the leftmost argument. The change will go out in the next release.

**Comment by pinpox** [comment]
@ogham If I'm reading the issues correctly, this is the only open issue for the `v0.10.0` milestone. Is  there anything else missing for the release? I'm waiting for the release, since I want to use a few of the fixes/missings added but want to keep exa installed from my distributions repository. Any estimation on  when `v0.10.0` will be released?

**Comment by ariasuni** [comment]
I checked and the current behavior of master is correct:

```
$ ../target/debug/exa -Gl
.rw-r--r-- 0 ariasuni  3 Jan 23:45 foo.txt
$ ../target/debug/exa -Gl | cat
.rw-r--r-- 0 ariasuni  3 Jan 23:45 foo.txt
$ ../target/debug/exa -GlT
drwxr-xr-x - ariasuni  3 Jan 23:45 .
.rw-r--r-- 0 ariasuni  3 Jan 23:45 └── foo.txt
```

I’m going to close this in my effort to triage bug open bug reports.

As for 0.10.0, [I gave my personal opinion there](https://github.com/ogham/exa/issues/673#issuecomment-753360257). In the meantime, I’ll continue seeing if I can answer to bug reports, and merge a few PRs.
