### ISSUE TITLE
[help wanted] Use threadpool::ThreadPool instead of a blocking channel of threads

### ISSUE THREAD

**Issue by byteprelude** [ogham/exa#63]
A few months ago I made [pull request #45](https://github.com/ogham/exa/pull/45) to stat the files in parallel. Back then the `ThreadPool` in `std` was in the process of being deprecated, so I used a less efficient approach of spawning a thread for each stat task and using a `sync_channel` to keep track of the thread capacity. Now that [`ThreadPool` is moved to a separate crate](http://doc.rust-lang.org/threadpool/threadpool/index.html), I tried going back to replacing the `(thread_capacity_tx, thread_capacity_rx)` hack with a `ThreadPool`. However, I ran into some lifetime issues that I wasn't able to get around. If anyone can get it working that's be great.

**Comment by ogham** [comment]
Hey @byteprelude, do you remember which lifetime errors you were getting?

I managed to replace the `sync_channel` with a `ThreadPool` from the crate you mention ([here's the commit, not merged yet](https://github.com/ogham/exa/commit/ea3a57eb971fad30280f3f8fcea04343b159eb51)) and it all seems to work. However I'm not sure if the lifetimes have changed since a month ago, or I've just missed something simple!

**Comment by byteprelude** [comment]
Lifetime rules probably haven't changed since then. My error must have been due to something silly I did, but I don't remember it. 

The changes look good. Thanks.

**Comment by ogham** [comment]
Wicked. I do silly stuff all the time, and I never remember it either.

**Comment by ogham** [comment]
(Fixed in 8c1e6d0799455593b6e991e96ce7bdf0221fafd3)
