### ISSUE TITLE
“exa” is harder to type than “ls”

### ISSUE THREAD

**Issue by wiso** [ogham/exa#676]
I like exa, but this is one big problem: ergonomics. "ls" is very easy to type, the two letters are on the middle row of the keyboad, where usually eight fingers lay when at rest.
On the contrary to type "exa" you are using only left hand and using keys on all the three rows of the keyboard.

This is preventing me to always use exa instead of ls.

Of course one can create an alias, but have you ever consider to change name?

**Comment by rwilhelm** [comment]
Same thoughts here... it's not a dealbreaker, but something like `lx` would be much more muscle-memory-friendly without overwriting `ls` with an alias. If you'd rename the whole thing to `lx` I'd save one alias in my zsh-config.

**Comment by max-sixty** [comment]
Why not alias `ls` to `exa`?

**Comment by ariasuni** [comment]
A few suggestions were made a while ago on issue #195, summarized here:

- `xa`: one letter less
- `lx`: l from ls, x from exa, could mean 'list extra' or 'list expanded' 'list exemplary'
- `la`: on the middle keyboard row (in qwerty) and it could stand for "list advanced"

Personally, I’ve always used aliases for `ls` because I use it all the time, and I did the same for exa. I’d expect people replacing core utilities like `ls` to know how to make aliases.

Also, changing the name has to be really worth it, because lots of people already know exa under its current name.

**Comment by arran-nz** [comment]
I think the name `la` is appropriate.

Assuming Qwerty:
- It's one the home row, as with `ls`
- It's symmetric, as with `ls` 
- 2 letters is better for frequently executed commands.
- List Advanced is easy to remember

**Comment by ogham** [comment]
For better or worse — though hopefully for better — "exa" is what the project's known as. And in my opinion, the name is suitable for an application with features, where `la` is more like the name of a script.

There's also #374  which has some alias discussion.
