### ISSUE TITLE
Color difference between date and directories

### ISSUE THREAD

**Issue by carlocaione** [ogham/exa#686]
Currently `exa` is displaying this by default:
![Screenshot from 2020-06-08 10-49-36](https://user-images.githubusercontent.com/357758/84011045-d3ecca00-a975-11ea-8061-781dfb426db9.png)
It would be nice to have the colors of the date and directories slightly different.

Also, is it normal the the directory icons are the only ones not colored?

![Screenshot from 2020-06-08 10-51-48](https://user-images.githubusercontent.com/357758/84011194-11e9ee00-a976-11ea-80cb-5336e8394ca6.png)

**Comment by ariasuni** [comment]
> It would be nice to have the colors of the date and directories slightly different.

What terminal emulator are you using? Most terminals offer the option to display “bright colors” in bold and often it’s on by default, so in my case I see a difference. You can also use `EXA_COLORS`.

It’s hard to find a color that works otherwise, since there could be other columns too. I guess blue was chosen because it’s the color that `ls --color` used (at least GNU ls).

I guess we would be open for change if your arguments are convincing but we can’t just change something because it looks bad on some terminal emulators; otherwise we would be even more constrained in color choices (see [That Annoying Shade of Blue](https://bsago.me/posts/that-annoying-shade-of-blue) for more context).

> Also, is it normal the the directory icons are the only ones not colored?

I see that the issue is happening on exa 0.9.0, but after testing it’s fixed in the development version.

**Comment by carlocaione** [comment]
Currently using `tilix` with `TERM==xterm-256color`. `tilix` has a `Show bold text in bright colors` option, it does changes some colors but (i.e. the color of the username) but not the colors for date and directories. Anyway, closing this issue since I got used to it so it doesn't bother me anymore ;)
