### ISSUE TITLE
when showing hard links don't render 1

### ISSUE THREAD

**Issue by maxandersen** [ogham/exa#693]
Using -H is great, but showing `1` for every file feels redundant and unnecessary visual clutter.

```
exa -bghHl --git --grid
Permissions Links  Size User Group Date Modified Git Name                 Permissions Links  Size User Group Date Modified Git Name
drwxr-xr-x      4     - max  staff 26 Jun  8:19   -I bin                  drwxr-xr-x     25     - max  staff 29 Jun  0:04   -I itests
drwxr-xr-x     19     - max  staff 29 Jun  0:20   -I build                .rw-r--r--        1.1Ki max  staff 26 Dec  2019   -- LICENSE
.rw-r--r--        7.1Ki max  staff 29 Jun  0:04   -- build.gradle         .rwxr--r--          224 max  staff 25 Jun  0:28   -N max.java
.rw-r--r--        2.8Ki max  staff 29 Jun  0:16   -- CONTRIBUTING.adoc    drwxr-xr-x     10     - max  staff 31 May 18:53   -I misc
.rw-r--r--        5.3Ki max  staff  6 Jun  8:08   -- CONTRIBUTORS.md      .rwxr-xr-x        1.1Ki max  staff 16 May 22:44   -- otp.java
.rw-r--r--        1.2Ki max  staff  7 Mar 16:39   -- devfile.yaml         drwxr-xr-x      3     - max  staff  6 Jun 23:56   -I out
drwxr-xr-x     50     - max  staff 25 Jun 22:06   -N examples             .rw-r--r--          243 max  staff  7 Mar 16:39   -- pipelines.puml
drwxr-xr-x      3     - max  staff 24 Dec  2019   -- gradle               .rw-r--r--         27Ki max  staff 26 Jun 23:49   -- readme.adoc
.rwxr-xr-x        5.2Ki max  staff 25 Dec  2019   -- gradlew              .rw-r--r--          458 max  staff 28 Jun 10:11   -- settings.gradle
.rw-r--r--        2.2Ki max  staff 25 Dec  2019   -- gradlew.bat          drwxr-xr-x      4     - max  staff 29 Jun  0:14   -- src
.rwxr--r--          223 max  staff 25 Jun 16:38   -N hv.java              drwxr-xr-x      5     - max  staff 28 Jun  9:14   -I target
```

vs

```
exa -bghHl --git --grid
Permissions Links  Size User Group Date Modified Git Name                 Permissions Links  Size User Group Date Modified Git Name
drwxr-xr-x      4     - max  staff 26 Jun  8:19   -I bin                  drwxr-xr-x     25     - max  staff 29 Jun  0:04   -I itests
drwxr-xr-x     19     - max  staff 29 Jun  0:20   -I build                .rw-r--r--      1 1.1Ki max  staff 26 Dec  2019   -- LICENSE
.rw-r--r--      1 7.1Ki max  staff 29 Jun  0:04   -- build.gradle         .rwxr--r--      1   224 max  staff 25 Jun  0:28   -N max.java
.rw-r--r--      1 2.8Ki max  staff 29 Jun  0:16   -- CONTRIBUTING.adoc    drwxr-xr-x     10     - max  staff 31 May 18:53   -I misc
.rw-r--r--      1 5.3Ki max  staff  6 Jun  8:08   -- CONTRIBUTORS.md      .rwxr-xr-x      1 1.1Ki max  staff 16 May 22:44   -- otp.java
.rw-r--r--      1 1.2Ki max  staff  7 Mar 16:39   -- devfile.yaml         drwxr-xr-x      3     - max  staff  6 Jun 23:56   -I out
drwxr-xr-x     50     - max  staff 25 Jun 22:06   -N examples             .rw-r--r--      1   243 max  staff  7 Mar 16:39   -- pipelines.puml
drwxr-xr-x      3     - max  staff 24 Dec  2019   -- gradle               .rw-r--r--      1  27Ki max  staff 26 Jun 23:49   -- readme.adoc
.rwxr-xr-x      1 5.2Ki max  staff 25 Dec  2019   -- gradlew              .rw-r--r--      1   458 max  staff 28 Jun 10:11   -- settings.gradle
.rw-r--r--      1 2.2Ki max  staff 25 Dec  2019   -- gradlew.bat          drwxr-xr-x      4     - max  staff 29 Jun  0:14   -- src
.rwxr--r--      1   223 max  staff 25 Jun 16:38   -N hv.java              drwxr-xr-x      5     - max  staff 28 Jun  9:14   -I target
```

I find the first one much easier on the eyes to identify number of files in the subdirectories.

**Comment by mschilli87** [comment]
I strongly disagree: If a file has one link pointing to it, I expect to see a `1`.

~If you really want to get rid of it, I'd suggest setting up an alias piping the output to `awk` using something along the lines of `$link_col == 1 {$link_col = ""}` instead of potentially breaking everybody else's output.~ I just noticed that piping would break the `--grid` ouput. :facepalm: 

Also not how other columns prefer `-` over an empty field for 'things that don't make sense'.
So either way you change would introduce inconsistencies that I find more bothersome than the `clutter` introduced by stating the fact that most files have only one associated link.

**Comment by maxandersen** [comment]
Just - would be fine too. Anything that make it not a number.

**Comment by mschilli87** [comment]
I still disagree. This column list the number of links to a file. For most files that is 1. You could also replace the calling user's name and group by `-` to remove 'clutter' from the corresponding columns. But all these kind of things do is to make the default output harder to interpret: While for you it might be clear that `-` means single link, other people (e.g. migrating from `ls` which lists single links files with a `1` in the corresponding column as well) might be confused by this.

I think a good solution would be to add a flag to allow piping of `--grid` output which will enable users to further modify the output at will (and setup an alias).

**Comment by maxandersen** [comment]
maybe consider a `--hide-defaults` option since I actually liked the idea of hiding current user since if its current user it not special.

just a thought.

**Comment by mschilli87** [comment]
Again: If you can pipe `--grid` output, you can do all sorts of extra changes by an alias. If you want, you can replace the current user by `root` and a single hard link by `-42`. If you like that, great. I think it should be possible to do that. That's why I like the idea of piping any standard output. But IMHO that still does not warrant a potentially huge number of extra arguments to satisfy each and every conceivable user preference. Do one thing and do it well. And empower the user to do his own thing by pipes. Just my 2ct. :wink:

**Comment by ogham** [comment]
This is an interesting suggestion! I gave it some thought.

It's true that files will only have one hard link the vast majority of the time. However, I came down on the side of keeping the number, because it doesn't fit with the reason exa uses `-` in columns: it's when the value doesn't make sense for the file kind, not when the value is special somehow. Directories always have their size hidden, they don't only have their size hidden when it's 4096; similarly, a file with a link count of 1 should still show the count of 1.

You can get something approaching what you want by using the `EXA_COLORS` environment variable to grey out the link count (`lc`), then set the link multiple colour (`lm`) back to red:

![Screenshot 2020-10-14 at 22 31 18](https://user-images.githubusercontent.com/503760/96047412-fc795900-0e6c-11eb-9d7c-39570d44f45a.png)
