### ISSUE TITLE
ls & exa differ for `-t`

### ISSUE THREAD

**Issue by fzakaria** [ogham/exa#696]
Here are the contents of `man ls` for **-t**
```
       --time=WORD
              with  -l,  show  time  as  WORD  instead of default modification time: atime or access or use (-u); ctime or status (-c); also use specified time as sort key if
              --sort=time (newest first)

       -t     sort by modification time, newest first
```

here are the contents of `man exa` for **-t**
```
       -t, --time=WORD
              which timestamp field to list (modified, changed, accessed, created)

```

Since **exa** uses `-t` as the same flag for `--time` it means I cannot copy over some muscle memory filters like:
```
ls -lrt
```
(sort by time reverse chronological)

I ran into this because I **alias** exa to ls since I really have enjoyed exa that much ! (Thanks!)
```
❯ which ls
ls: aliased to exa --color=auto
```

**Comment by fzakaria** [comment]
For those interesting; in **exa** the analogous command is **exa -lrm**; *m* is short for **--sort=modification**

**Comment by laur89** [comment]
Also note the sorting order differs between ls & exa, which is why you had to provide `-r` to exa in your example above.

I'm quite sure following commands should sort the files in same order, yet they're opposite:

```
exa -l --sort=newest
ls -lt
```

**Comment by fzakaria** [comment]
I find the lack of support for `ls -lrt` and the wrong order (@laur89 you are right!) one of the more frustrating aspects of having `alias ls=exa`

Excellent software otherwise :+1: 
I understand the request is a bit of a PITA since it's "hey make your software behave more like another software!" but the argument to _alias_ would help give **exa** I believe a lot more adoption.

**Comment by mschilli87** [comment]
I honestly think that with https://github.com/ogham/exa/issues/621, hundreds of open issues and not much going on for many month (regardless of PR being opened and issues added), anything stopping people from switching to exa because they like the colors is a good thing. If this were stable maintained software with an active community, I'd aggree we should push for more closely matching 'upstream' to ease transitions (cf. Neovim or NeoMutt). But given the current state of exa, this 'problem' seems so minor that it would actually make me sad if this out of all would get the maintainer's attention.

**Comment by fzakaria** [comment]
@mschilli87 is there a more supported fork ?
We should change some of the package management (NixPkgs) to point to it instead.

**Comment by mschilli87** [comment]
@lespea mentioned merging some work on top of this one but I am not aware of an actually maintained fork in the sense that I could recommend it. I think many people are unhappy with the state of exa but nobody has (read: is willing to take) the time to chnange it. Note that this includes me and is not meant as a offense to anyone. I rather interpret this as while exa is a nice addition, nobody feels it is really important to replace `ls`. :wink:

**Comment by johnchurchill** [comment]
Not supporting the same switches that ls does is kind of a big deal. It's not just muscle memory and the inconvenience of having to remember which system you're shelled in on to use which switches. Imagine you are working in a team that uses a deployment script that does LATEST_BUILD=$(cd ${BUILDSDIR}; ls -t | grep \.war$ | head -1) ... oops it doesn't work for you because you are using exa. So you have to unalias ls before you can use the script, or request that the script be changed to unalias ls for that tiny percentage of people who use an incompatible ls substitute like exa.

**Comment by evandena** [comment]
When running "exa -l --sort=newest" files with the same modified time seem to be randomly ordered, where "ls -latr" is consistent.
Is there a way for exa to behave similar to ls in this manner?

**Comment by zsimic** [comment]
+1 I wish `exa -t` was the same as `ls -t`

Especially since the `--time FIELD` seems to be quite the niche thing... (I can totally see it as very seldom used)

It would be great if:
- `-t` was the same as `ls -t` (ie: change current `exa -m` to be simply `exa -t`)
- `--time` is fine without a one-letter shortcut I think...

**Comment by ariasuni** [comment]
Closing this in favor of #519.
