### ISSUE TITLE
-? doesn't work with zsh

### ISSUE THREAD

**Issue by kbknapp** [ogham/exa#70]
I can't speak to exactly why, as I'm not familiar with zsh internals, but `-?` doesn't work as you get a 

```
$ exa -?
zsh: no matches found: -?
```

Yet things such as `-@` seem to work just fine. This isn't a huge issue, as `--help` works just fine, but just FYI since I'm sure there are some other zsh users out there.

**Comment by ogham** [comment]
It's because zsh uses `?` as a wildcard. You know how using `*` in a command expands it to every file with the star matching part of the text? `?` does the same, but only for a single character. So here, it's trying to expand it to every two-character-long file where the first character is a hyphen, and you don't have any, so it complains.

There's nothing I can do about this, since it's done by zsh rather than exa... `--help` is pretty much standard, though, and it has that, at least!

**Comment by kbknapp** [comment]
Oh ok, thanks for clearing it up! I didn't think it was an issue with `exa` I was just curious if it's been addressed before, or was in any help docs somewhere that I missed.

Maybe that'd be something worth mentioning in the help text? Something as simple as 'Show list of command line options (If using zsh, must use --help)` to prevent further issues being filed :P

**Comment by ogham** [comment]
Thing is, it's also a wildcard in fish, and I don't want to have to go through every shell just to find out what's supported and what isn't! That way lies maaaaaaaadness. Hopefully anyone in the future just finds this issue!

**Comment by kbknapp** [comment]
Gotcha, good point! :)
