### ISSUE TITLE
'make install' gives 'Permission denied'

### ISSUE THREAD

**Issue by tomory** [ogham/exa#701]
Centos 7 doesn't provide GLIBC_2.18, so I compiled exa according to the instructions given for Fedora (`make install`). The compilation stage goes fine but the install stage errors out with 'Permission denied'.

- I could `sudo cp -p target/release/exa /usr/local/bin` and get a working executable, but of course then I would miss out on the man page.
- I tried `sudo make install` but that results in errors that I don't know how to work around:
> ```
> cargo build --release --no-default-features --features "default"
> error: no override and no default toolchain set> 
> make: *** [target/release/exa] Error 1
> ```
This might be a good thing to fix properly. In the meantime, what's a quick and dirty way to get the man page where it needs to go? I don't even know where it is in the directory structure.

Thanks.

**Comment by nkoppel** [comment]
Modify this line in the Makefile:

`install-exa: target/release/exa`

to this:

`install-exa:`

then

`$ make build`
`$ sudo make install`

The issue was that `sudo make install` would try to build exa, and that rust hadn't been set up for the root user.

**Comment by ogham** [comment]
The Makefile has been removed because it kept causing problems like this — it's tough to keep up with the requirements for all OSes and everyone's particular setups. I feel like all exa should know how to do is build itself, not install itself. I've added some instructions to the README for how to install the man page, which were missing before (thanks for pointing that out)

> The issue was that sudo make install would try to build exa, and that rust hadn't been set up for the root user.

Yeah, this was what was happening.
