### ISSUE TITLE
Switch from make to just breaks Homebrew formula when installing from HEAD

### ISSUE THREAD

**Issue by qbedard** [ogham/exa#749]
The Homebrew formula still expects to use make to build exa. We'll either need to update the formula to use a different install command based on the version/commit or re-add a Makefile that just invokes just.

**Comment by timbedard** [comment]
I opened https://github.com/Homebrew/homebrew-core/pull/62812 to have Homebrew just use cargo directly rather than going through make/just.

**Comment by ogham** [comment]
Ah, thank you for raising this issue with the Homebrew team! I didn't realise that the formula was still dependent on `make`.

Looking at your change, I think using `cargo install` with Homebrew's arguments is a better idea than using `make` anyway — it means the package manager knows how to install exa, rather than exa knowing how to install itself for all possible OSes (which is something I've been wary about getting wrong).

Thanks again.

**Comment by timbedard** [comment]
That update is merged, but now the `contrib` -> `completions` change is breaking completion installation, which causes the install to fail. I'll see if I can find some time to fix that today.

**Comment by timbedard** [comment]
https://github.com/Homebrew/homebrew-core/pull/62876

**Comment by timbedard** [comment]
Merged and looking good.
