### ISSUE TITLE
The meaning of the letters used to show git status are not documented

### ISSUE THREAD

**Issue by ariasuni** [ogham/exa#778]
exa displays two columns, representing the staged and unstaged states. Meaning of symbols by reading [the source code](https://github.com/ogham/exa/blob/v0.10.0/src/output/render/git.rs):

- Not modified: `-`
- New: `N`
- Modified: `M`
- Deleted: `D`
- Renamed: `R`,
- Type changed: `T`
- Ignored: `I`
- Conflicted: `U` (unmerged)

This should be added exa’s documentation.

**Comment by msorens** [comment]
Yes, please! (Thank you for doing the digging, @ariasuni ! I was just about to do the same thing.)

I would like to make a further suggestion: use the same letters that git uses where possible. So close! 😁 , but new should be `A` instead of `N` at least (from https://git-scm.com/docs/git-status):

![image](https://user-images.githubusercontent.com/6817500/104143336-e5ff7280-5373-11eb-8ea1-fe4f172e47e1.png)

**Comment by ariasuni** [comment]
@ogham What do you think of the suggestion of @msorens, should exa use `A` for added to follow git’s already established convention?

**Comment by francoibanezweb** [comment]
@ariasuni Do you know if it was added to the documentation? Or what convention was used in the end?

**Comment by eggbean** [comment]
They are the same letters using by `git whatchanged`, but `N` instead of `A` and the addition of `U` and `I`.

**Comment by ariasuni** [comment]
The convention is unchanged, and it’s in the man page.

exa is unmaintained, so if you have further comments, please look at [the active fork eza](https://github.com/eza-community/eza) instead (see https://github.com/ogham/exa/issues/1243). Also see https://github.com/ogham/exa/issues/1243
