### ISSUE TITLE
Would love to get a new release, since there are cool changes in master

### ISSUE THREAD

**Issue by ChristophP** [ogham/exa#809]
Hello, thanks for making exa. :-)
I noticed the last release is almost from 9 months ago. There are some commits in master which would be great to have such as this one https://github.com/ogham/exa/pull/653 but `brew` only unstalls the 0.9.0 verison of exa which doesn't have it yet.

Are there any plans for creating a new release soon?

**Comment by kidonng** [comment]
Big sur users can use [my Homebrew tap](https://github.com/kidonng/homebrew-malt) (`brew install brew install kidonng/malt/exa-mod`), which provides bottle for latest master plus my PR to support config file/env.

**Comment by cho-m** [comment]
More precisely, the last release (0.9.0) was Jul 2019, so we are closing in on 2 years since release.
The prior release (0.8.0) was Sep 2017.

This has been requested a few times (see: #621 #697), but currently only the author has permissions to create a release, so the next release is blocked on his return (#673).

Some possible choices for now (from lowest effort to most) are:
- use someone else's Homebrew tap, like the one above,
- **Homebrew source build:** `brew install exa --HEAD` should build the latest source on Intel Macs. May not work natively on M1 Macs since `pandoc` currently isn't building on arm64.
- **Rust Cargo source build:** `cargo install --git https://github.com/ogham/exa`

**Comment by ariasuni** [comment]
This has been requested *a lot*:

https://github.com/ogham/exa/issues/798#issuecomment-775723674
https://github.com/ogham/exa/issues/780#issuecomment-759345277
https://github.com/ogham/exa/issues/785#issuecomment-757339474
https://github.com/ogham/exa/issues/731#issuecomment-687306334
https://github.com/ogham/exa/issues/711#issuecomment-727257228
https://github.com/ogham/exa/issues/697
https://github.com/ogham/exa/issues/629#issuecomment-630942020
https://github.com/ogham/exa/issues/621
https://github.com/ogham/exa/issues/558#issuecomment-593955317
https://github.com/ogham/exa/issues/526#issuecomment-769765278
https://github.com/ogham/exa/issues/456#issuecomment-471315578
etc.

Hopefully people will see this issue and put a thumbs up on its first comment instead of filling my inbox.

**Comment by seguri** [comment]
@ariasuni can you ask @ogham to take over this project?

**Comment by tshirtman** [comment]
If the repository owner is unresponsive, the way to go could be to create a github org to manage the project, fork the project there, update this readme to redirect to it (or better "move" the project to it, if someone has the rights for that, so github handles the redirection), and create a team of contributors to manage that organization.

It's sad to see a project die, but it's even more sad when it has contributors that care about it but are just not empowered enough to keep it alive.

**Comment by ariasuni** [comment]
As much as I try to give love to this project, answer to issues, review PRs, etc., I have a hard time managing my own life so I can’t do that even if I wanted to.

If someone really wants to set-up an organization, work regularly on exa, and create a new website maybe, I would gladly contribute like I’m doing here — especially since I’m a long-time contributor, so I understand better how the project is organized and its philosophy than most occasional contributors.

Let’s say I try to reach to @ogham again to see what’s possible, and if I don’t hear back in a month we do this?

In the meantime, it’s still possible to contribute and since it’s Free Software, the code won’t be lost and you’ll still be able to make a fork later. And to be honest, it’s a big responsibility to merge stuff so if people would like to get involved and review code, and if people would like to triage issues and fix them to keep their number low, that would be awesome.

**Comment by cho-m** [comment]
New release today for anyone who didn't see it: https://github.com/ogham/exa/releases/tag/v0.10.0

**Comment by ChristophP** [comment]
Awesome 👍 Thanks. Closing 😎
