### ISSUE TITLE
Icons need some extra space for thin fonts

### ISSUE THREAD

**Issue by GoldsteinE** [ogham/exa#828]
I use Iosevka, and running `exa --icons` gives me output like this:
![image](https://user-images.githubusercontent.com/12019211/113480569-8fe72a80-949d-11eb-8efb-a17b786728e4.png)
There should be an option to add some spaces after icons for thinner fonts.

**Comment by ariasuni** [comment]
The `EXA_ICON_SPACING` variable [has been introduced to handle this](https://github.com/ogham/exa/commit/51be9f4c43e61bbea61e70e1459e494207d1d979), though a new release of exa with this feature has not been released yet.

Thanks for the report, I’m gonna close this since it’s been fixed. If you’re eager to use that, you can still compile your own version of exa.
