### ISSUE TITLE
exa always shows numeric UIDs/GIDs for non-local users

### ISSUE THREAD

**Issue by eflyon** [ogham/exa#900]
OS: RHEL 7.9
exa version: 0.10.1 (from exa-linux-x86_64-musl-v0.10.1.zip on the releases page)

```
$ exa -lg
.rw-r--r--@ 0 ntp   ntp   24 Jun 12:53 bar
.rw-r--r--@ 0 14485 14034 24 Jun 12:53 baz
$ ls -l
total 0
-rw-r--r--. 1 ntp   ntp    0 Jun 24 12:53 bar
-rw-r--r--. 1 elyon foobar 0 Jun 24 12:53 baz
```
It seems that exa doesn't show user names unless the user is defined in `/etc/passwd` and doesn't show group names unless the group is defined in `/etc/groups`.  This computer is on a network where most users and groups are managed in Active Directory.

I can't test with the glibc version since the system libc is too old (RHEL7 has 2.17, binary needs 2.18).

**Comment by ariasuni** [comment]
Thanks for the report! I’ll close this since this problem is already tracked in #671.

Following your report, I investigated for a few hours here and there, so please read [the comment I just wrote on #671](https://github.com/ogham/exa/issues/671#issuecomment-869032782), if you can help me gather more information about this it would be great.
