### ISSUE TITLE
Installation error in exa

### ISSUE THREAD

**Issue by Mohitkumar6122** [ogham/exa#912]
When I used the command ``` sudo apt install exa ```<br>
It is showing me the error as ``` Unable to locate package exa ```

- The version of exa being used (`exa --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.
![image](https://user-images.githubusercontent.com/47894634/125513875-ff469983-18f9-4f80-be9c-01ad96e767ed.png)

---

**Comment by gek169** [comment]
what distro is this

**Comment by deadcoder0904** [comment]
I can't install it in my Windows 10 using `cargo install exa` either. Every other Rust package like `fd`, `kondo`, `pastel`, etc... are easily installed using `cargo install`. My error:

> error[E0433]: failed to resolve: could not find `unix` in `os`
  --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\users-0.11.0\src\base.rs:36:14
   |
36 | use std::os::unix::ffi::OsStrExt;
   |              ^^^^ could not find `unix` in `os`

**Comment by ariasuni** [comment]
exa is available since «On Ubuntu 20.10 (Groovy Gorilla) and later», what version of Ubuntu are you using?

If you’re using a version of Ubuntu too old:
- You can follow the instructions [here](https://github.com/ogham/exa#manual-installation-from-github) (note that the instructions on the website are a little bit outdated, there’s a second man page that needs to go to `/usr/share/man/man5` and the completions files, well, … I really should write up-to-date instructions in the README…).
- You can install exa by using `cargo install exa`, if you have rust and cargo installed, see [here](https://github.com/ogham/exa#cargo).
- Also, someone created a PPA for Ubuntu 20.04 but it’s totally unofficial: https://github.com/ogham/exa/issues/783#issuecomment-877973708

**Comment by Mohitkumar6122** [comment]
> what distro is this

![image](https://user-images.githubusercontent.com/47894634/125624243-e2654309-59d3-4f23-8647-c220b4f78d5d.png)

**Comment by Mohitkumar6122** [comment]
> exa is available since «On Ubuntu 20.10 (Groovy Gorilla) and later», what version of Ubuntu are you using?
> 
> If you’re using a version of Ubuntu too old:
> 
> * You can follow the instructions [here](https://github.com/ogham/exa#manual-installation-from-github) (note that the instructions on the website are a little bit outdated, there’s a second man page that needs to go to `/usr/share/man/man5` and the completions files, well, … I really should write up-to-date instructions in the README…).
> * You can install exa by using `cargo install exa`, if you have rust and cargo installed, see [here](https://github.com/ogham/exa#cargo).
> * Also, someone created a PPA for Ubuntu 20.04 but it’s totally unofficial: [exa is not in repositories of Ubuntu 20.04 (latest LTS)/WSL2 #783 (comment)](https://github.com/ogham/exa/issues/783#issuecomment-877973708)

I am using Ubuntu 20.04

**Comment by ariasuni** [comment]
Yup, so I’m gonna close this. Feel free to comment here again if you have an issue with the installation, I’ll still get the notification and will try to help you, but please be mindful of my time.

There was some discussion to improve the website’s instructions so users don’t get confused: https://github.com/ogham/exa/issues/829

@deadcoder0904 see #32 and #820, there is ongoing work for Windows support but it takes a while…
