### ISSUE TITLE
Unknown argument --icons

### ISSUE THREAD

**Issue by John15321** [ogham/exa#917]
- The version of exa being used (`exa --version`)
`exa v0.8.0`
- The command-line arguments you are using
`exa --icons`
- Your operating system and hardware platform
`Raspberry Pi 4 4GB, Raspbian OS (raspbianOS is only 32bit)`

I just want to show icons, I don't know why but on another Raspberry Pi, that has the same hardware etc it works. I installed exa using cargo (`cargo install exa`) in both cases.

![image](https://user-images.githubusercontent.com/56229312/126904129-4c8b80eb-2db0-4aa3-87ae-7ece414781ac.png)

As you can see in the screen shot I Have needed fonts etc, so I really don't understand where is the problem 😔

---

**Comment by ariasuni** [comment]
You version of exa is too old. `--icons` has been added in exa 0.9.0.

If you want to use this feature, you should install a newer version manually, since your distribution is stuck on 0.8.0.
https://github.com/ogham/exa#manual-installation-from-github

There’s an unofficial PPA as well: https://github.com/ogham/exa/issues/783#issuecomment-877973708

**Comment by scott-parkhill** [comment]
This is still an issue more than a year from the last activity on this issue.
