### ISSUE TITLE
Have Travis actually run a Linux build

### ISSUE THREAD

**Issue by ogham** [ogham/exa#96]
Currently, all Travis does is run tests. It would be nice if it would actually run an exa binary to automatically check that the binary it builds actually *runs without crashing*.

(I'm looking at you, @petevine :smiling_imp:)

**Comment by petevine** [comment]
Probably a good idea, unsafe can be tricky - why me though? ;)

I'd like to clarify the comment I'd deleted: it wasn't just a crash caused by a broken compiler (I'd managed to reproduce on 1.5 stable too) but rather by some artifacts from a broken compiler that `cargo clean` didn't manage to get rid of.

**Comment by ogham** [comment]
Ah, I did wonder what was going on with your problem report. (It even spooked me a little when I couldn't find it). Come to think of it, I think I've had the same thing happen to me before.

But I wouldn't have been worried if I knew I'd actually run a Linux build and not just its tests.

**Comment by ogham** [comment]
This got fixed in 8cadfa00492f789eb733538908626b41931456a1 and I forgot to mention this issue in the commit.
