### ISSUE TITLE
Get exa on NixPkgs

### ISSUE THREAD

**Issue by bsima** [ogham/exa#98]
Does anyone else use [NixOS](https://nixos.org)? I've started using it quite heavily and would like to see exa in the Nix package repository. I've never submitted anything to Nix before, so I'm not familiar with how it works, but I imagine I'll get to it soon because I miss exa on my machines :)

**Comment by ogham** [comment]
I've heard good things about Nix, but not enough to know how its packages work. But I'd love to have it on there!

**Comment by ehegnes** [comment]
I'd be glad to write a Nixpkg entry for this! I don't use NixOS, but I do use their package manager occasionally. My only question is, "where in the nixpkg tree does this belong?" You can view the tree [here](https://github.com/NixOS/nixpkgs/tree/master/pkgs).

I vote for `applications/misc/exa`. Notably, `tree` is in `tools/system/`, but I don't quite agree with that. Regardless of the placement, I'll post soon with more information about the completed file.

**Comment by bsima** [comment]
I think either `applications/misc` or `tools/misc` would be appropriate. I guess the Nixpkg guys would know best, and they'd steer you in the right direction after you open the initial PR.

Thanks for grabbing this @ehegnes :)

**Comment by ehegnes** [comment]
As can be seen in the above PR, I have completed the Nix package for `exa`! How exciting. Hopefully I didn't muck anything up too badly and the Nix folk merge it soon.

Due to some stabilization (removal of feature macros) [since the latest v0.4.0 tag](https://github.com/ogham/exa/compare/v0.4.0...master), I have cited the package version as a git revision rather than a tagged release. That way, `exa` will compile on Nix without messing with beta or nightly Rust builds. I will update the Nix package to use a proper release version as soon as the next tagged release of `exa` is specified.

**Comment by ehegnes** [comment]
This issue can be closed! The package has been merged.

**Comment by ehegnes** [comment]
@bsima please feel free to email me directly if you experience any future issues with the package or if I'm slow to update. I've listed myself as a maintainer, but I don't use NixOS, so I'll be updating the package periodically, but possibly not as frequently as you'd like.

**Comment by ogham** [comment]
Good to hear!
